### ISSUE TITLE
add trace support for ARM

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1668]
Initial support via #1551 focused on basic blocks only.  There is a bunch of x86-specific trace building code that needs to be ported.

**Comment by derekbruening** [comment]
This is old, but is probably still representative:

```
# gdb --args bin32/drrun -debug -early -loglevel 4 -c api/bin/libinscount.so -- ~/test/simpleasm-t32 

Hello world!
Hello world!
Hello world!
Hello world!
<Source operand #0 has wrong type/size>

Breakpoint 3, external_error (file=0x2a2b806c "/home/derek/dr/git/src/core/arch/arm/encode.c", line=2443, 
    msg=0x2a2b88b8 "instr_encode error: no encoding found (see log)") at /home/derek/dr/git/src/core/utils.c:196
196	{
(gdb) bt
#0  external_error (file=0x2a2b806c "/home/derek/dr/git/src/core/arch/arm/encode.c", line=2443, 
    msg=0x2a2b88b8 "instr_encode error: no encoding found (see log)") at /home/derek/dr/git/src/core/utils.c:196
#1  0x2a1fe7f8 in instr_encode_arch (dcontext=0x50797b20, instr=0x507eb450, 
    copy_pc=0x507e6d8c "\313\362\377k\230m~P", final_pc=0x507e6d8c "\313\362\377k\230m~P", check_reachable=false, 
    has_instr_opnds=0x0, assert_reachable=false) at /home/derek/dr/git/src/core/arch/arm/encode.c:2443
#2  0x2a1f6126 in instr_encode_ignore_reachability (dcontext=0x50797b20, instr=0x507eb450, 
    pc=0x507e6d8c "\313\362\377k\230m~P") at /home/derek/dr/git/src/core/arch/encode_shared.c:105
#3  0x2a203402 in instrlist_disassemble (dcontext=0x50797b20, tag=0x80a0 "\243\361\001\003", ilist=0x507e9690, 
    outfile=1953) at /home/derek/dr/git/src/core/arch/disassemble_shared.c:1408
#4  0x2a173cca in extend_unmangled_ilist (dcontext=0x50797b20, f=0x507f22e0)
    at /home/derek/dr/git/src/core/monitor.c:251
#5  0x2a177d00 in internal_extend_trace (dcontext=0x50797b20, f=0x507f22e0, prev_l=0x0, add_size=144)
    at /home/derek/dr/git/src/core/monitor.c:1711
#6  0x2a17abde in monitor_cache_enter (dcontext=0x50797b20, f=0x507f22e0)
    at /home/derek/dr/git/src/core/monitor.c:2411
#7  0x2a0e527e in dispatch (dcontext=0x50797b20) at /home/derek/dr/git/src/core/dispatch.c:188
```
