### ISSUE TITLE
CRASH opcodes sample running url_unittests

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1699]
Running without --single-process-tests seems to crash about 1 in every 5 runs:

```
# bin32/drrun -c api/bin/libopcodes.so -- ~/chromium/out_arm/Release/url_unittests
  Client opcodes is running
  IMPORTANT DEBUGGING NOTE: batches of tests are run inside their
  own process. For debugging a test inside a debugger, use the
  --gtest_filter=<your_test_name> flag along with
  --single-process-tests.
  Using sharding settings from environment. This is shard 0/1
  Using 8 parallel jobs.
  <Application /home/derek/chromium/out_arm/Release/url_unittests (30235).
  DynamoRIO Sample Client 'opcodes' internal crash at PC 0x49af3000.  Please
  report this at http://dynamorio.org/issues.  Program aborted.
  Received SIGSEGV at pc 0x49af3000 in thread 30235
  Base: 0xb0000000
  Registers:  r0 =0x480086b0 r1 =0x0000761b r2 =0x00800000 r3 =0x00000001
              r4 =0xb6141460 r5 =0xb5941460 r6 =0xb59414c0 r7 =0xb6140338
              r8 =
  version 5.0.16576, custom build
  -no_dynamic_options -client_lib
  '/home/derek/dr/git/build_local_rel/api/bin/libopcodes.so;0;' -code_api
  -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject
  -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list ''
  -no_native_exec_managed_code -no_indcall2direct 
  0xb59414c0 0xb6bf6174
  0xb61414c0 0xb59414c0
  0xb69414c0 0xb61414c0
  0xb6bf6174 0xb69414c0
  0xb59414c0 0xb6bf6174
  0xb61414c0 0xb59414c0
  0xb69414c0 0xb61414c0
  0xb6bf6174 0xb69414c0
  0xb59414c0 0xb6bf6174
  0xb61414c0 0xb59414c0
  0xb69414c0 0xb61414c0
  0xb6bf6174 0xb69414c0
  0xb59414c0 0xb6bf6174
  0xb61414c0 0xb59414c0
  0xb69414c0 0xb61414c0>
  Failed to get out-of-band test success data, dumping full stdio below:

  [1/76] GURLTest.Resolve (UNKNOWN)
```

But I can't reproduce it easily, have to run in a loop:

```
<Application /home/derek/chromium/out_arm/Release/url_unittests (8418).  DynamoRIO Sample Client 'opcodes' internal crash at PC 0x55e0f000.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x55e0f000 in thread 8418
Base: 0xb0000000
Registers:  r0 =0x00000000 r1 =0x0000000c r2 =0x00000000 r3 =0xb6bed6a8
        r4 =0x00000000 r5 =0xb6153328 r6 =0x00000000 r7 =0xb6153338
        r8 =0

(gdb) x/10i 0x55e0f000
   0x55e0f000:  andeq   r0, r0, r0
   0x55e0f004:  andeq   r0, r0, r0
```

Debug build hit "failed to translate" once but can't repro a crash:
```
  Using sharding settings from environment. This is shard 0/1
  Using 8 parallel jobs.
  <-- parent 11155 forked child 11179 -->
  <-- parent 11155 forked child 11181 -->
  <-- parent 11155 forked child 11184 -->
  <(1+x) Handling our fault in a TRY at 0x711fc8f4>
  <failed to translate>
  <Application /home/derek/chromium/out_arm/Release/url_unittests (11184).  Application exception at PC 0x00000000.  
  Signal 11 delivered to application as default action.
  Callstack:
          0xb6c69000  
          0x0b02f04f  
  >
  <-- parent 11155 forked child 11212 -->
```

**Comment by derekbruening** [comment]
Back to release:

```
<Application /home/derek/chromium/out_arm/Release/url_unittests (21351).  DynamoRIO Sample Client 'opcodes' internal crash at PC 0xb0094514.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0xb0094514 in thread 21351
Base: 0xb0000000
Registers:  r0 =0x00000003 r1 =0x00000000 r2 =0x47ce0021 r3 =0x00000000
        r4 =0x00000000 r5 =0x47ce0020 r6 =0x00000000 r7 =0x00000001
        r8 =

(gdb) add-symbol-file '/home/derek/dr/git/build_local_rel/lib32/release/libdynamorio.so' 0xb0022350

#4  0xb005c4e2 in report_dynamorio_problem (dcontext=<optimized out>, dumpcore_flag=1, exception_addr=<optimized out>, 
    report_ebp=0x4 <Address 0x4 out of bounds>, 
    fmt=0xb00ce824 "%s %s at PC 0x%08x\nReceived SIG%s at%s pc 0x%08x in thread %d\nBase: 0x%08x\nRegisters:  r0 =0x%08x r1 =0x%08x r2 =0x%08x r3 =0x%08x\n\tr4 =0x%08x r5 =0x%08x r6 =0x%08x r7 =0x%08x\n\tr8 =0x%08x r9 =0x%08x r"...)
    at /home/derek/dr/git/src/core/utils.c:2261
#5  0xb00af932 in abort_on_fault (dcontext=0x47ce0020, dumpcore_flag=<optimized out>, pc=<optimized out>, sc=<optimized out>, 
    prefix=0xb6efbcbc "DynamoRIO Sample Client 'opcodes'", signame=0xb00ce99c "SEGV", where=0xb00ca880 "")
    at /home/derek/dr/git/src/core/unix/signal.c:2882
#6  0xb00b3b4c in abort_on_DR_fault (where=<optimized out>, signame=<optimized out>, sc=0x47d4a724, 
    pc=0xb0094514 "#\210\003\364hB\262\365hO\f\320\003\364pC\263\365pO\aР\034\020\275\372\367\311\376\003(\356\320 \035\020\275 \035\020\275", dcontext=0x47ce0020) at /home/derek/dr/git/src/core/unix/signal.c:2919
#7  master_signal_handler_C (sig=11, siginfo=<optimized out>, ucxt=0x47d4a710, xsp=0x47d4a690 "\v")
    at /home/derek/dr/git/src/core/unix/signal.c:4202

(gdb) x/4i 0xb0094514 
   0xb0094514 <decode_next_pc+8>:       ldrh    r3, [r4, #0]
   0xb0094516 <decode_next_pc+10>:      and.w   r2, r3, #59392  ; 0xe800

  uc_mcontext = {
    trap_no = 0xe, 
    error_code = 0x17, 
    oldmask = 0xfffbf2f7, 
    arm_r0 = 0x3, 
    arm_r1 = 0x0, 
    arm_r2 = 0x47ce0021, 
    arm_r3 = 0x0, 
    arm_r4 = 0x0, 
    arm_r5 = 0x47ce0020, 
    arm_r6 = 0x0, 
    arm_r7 = 0x1, 
    arm_r8 = 0x47d4ac90, 
    arm_r9 = 0x8, 
    arm_r10 = 0x47d4aa60, 
    arm_fp = 0x4, 
    arm_ip = 0x47ce0020, 
    arm_sp = 0x47d4aa00, 
    arm_lr = 0xb0094533, 
    arm_pc = 0xb0094514, 
    arm_cpsr = 0x600f0030, 

(gdb) bt
#0  decode_next_pc (dcontext=<optimized out>, pc=0x0) at /home/derek/dr/git/src/core/arch/arm/decode.c:2571
#1  0xb0094548 in decode_sizeof (dcontext=<optimized out>, pc=0x0, num_prefixes=<optimized out>)
    at /home/derek/dr/git/src/core/arch/arm/decode.c:2587
#2  0xb00b05cc in execute_default_action (dcontext=0x47ce0020, sig=0, frame=<optimized out>, sc_orig=0x47d4aaec, from_dispatch=false)
    at /home/derek/dr/git/src/core/unix/signal.c:4838
#3  0xb00b199e in execute_default_from_cache (sc_orig=0x47d4aaec, frame=0x47d4ac90, sig=<optimized out>, dcontext=<optimized out>)
    at /home/derek/dr/git/src/core/unix/signal.c:4894
#4  handle_client_action_from_cache (dcontext=<optimized out>, sig=<optimized out>, action=<optimized out>, our_frame=0x47d4ac90, 
    sc_orig=0x47d4aaec, blocked=false) at /home/derek/dr/git/src/core/unix/signal.c:2838
#5  0xb00b1fcc in execute_handler_from_cache (access_address=0x0, f=0x0, sc_orig=0x47d4aaec, our_frame=0x47d4ac90, sig=4, 
    dcontext=0x47ce0020) at /home/derek/dr/git/src/core/unix/signal.c:4310
#6  record_pending_signal (dcontext=0x47ce0020, sig=4, ucxt=0x47d4ad10, frame=0x47d4ac90, forged=false, access_address=0x0)
    at /home/derek/dr/git/src/core/unix/signal.c:3443
#7  0xb00b395c in master_signal_handler_C (sig=<optimized out>, siginfo=0x47d4ac90, ucxt=0x47d4ad10, xsp=0x47d4ac90 "\004")
    at /home/derek/dr/git/src/core/unix/signal.c:4276
```

The code is:

```
    byte *pc = (byte *) sc->SC_XIP;
    <...>
                instr_sz = decode_sizeof(dcontext, (byte *) sc_orig->SC_XIP,
                                         NULL _IF_X64(NULL));
                if (instr_sz != 0 &&
                    instr_sz == decode_sizeof(dcontext, pc, NULL _IF_X64(NULL)) &&
```

I suspect this is the same as the Debug failure to translate, which is why
the 1st one is ok but the 2nd one crashes w/ a NULL pc.

Now to the signal we were handling when we crashed:

```
(gdb) p /x *sc_orig
$5 = {
  trap_no = 0x6, 
  error_code = 0x0, 
  oldmask = 0x0, 
  arm_r0 = 0x49208c98, 
  arm_r1 = 0x0, 
  arm_r2 = 0xb6dd2000, 
  arm_r3 = 0x400, 
  arm_r4 = 0xb6bc3a78, 
  arm_r5 = 0xb6aad220, 
  arm_r6 = 0xb6bc46a8, 
  arm_r7 = 0x0, 
  arm_r8 = 0x0, 
  arm_r9 = 0x1, 
  arm_r10 = 0x47d0d000, 
  arm_fp = 0x0, 
  arm_ip = 0xb6b0c171, 
  arm_sp = 0xbe97f408, 
  arm_lr = 0x47fd1005, 
  arm_pc = 0x47fd1e98, 
  arm_cpsr = 0x200f0010, 

(gdb) set arm fallback-mode arm  
(gdb) x/10i 0x47fd1e98         
   0x47fd1e98:                  ; <UNDEFINED> instruction: 0xffff0fe0
   0x47fd1e9c:                  ; <UNDEFINED> instruction: 0x47eabb30
   0x47fd1ea0:  strblt  r6, [r6], r4, lsr #27
   0x47fd1ea4:  strbmi  r11, [r7, r1, lsr #11]!
```

looks more like data than code:

```
(gdb) x/30wx 0x47fd1e98-40
0x47fd1e70:     0x00000000      0xb00a8fd4      0x00000000      0xb00a8fd4
0x47fd1e80:     0xb6b08aa0      0x47eba22c      0xb6b08a60      0x47eba55d
0x47fd1e90:     0xb6bcf520      0x47ebc6e9      0xffff0fe0      0x47eabb30
0x47fd1ea0:     0xb6c66da4      0x47e7b5a1      0xb6b3c0a0      0x47dd9890
0x47fd1eb0:     0xb6c66ce4      0x47e7b865      0xb6b3cbe0      0x47de78cd
```

why is lr pointing into the cache?  in particular, it's in the middle of
our stub-final ldr into pc:

```
(gdb) x/10i 0x47fd1005-24
   0x47fd0fed:  str     r4, [r6, #4]
   0x47fd0fef:  str     r2, [r4, #100]  ; 0x64
   0x47fd0ff1:  str     r3, [r4, #104]  ; 0x68
   0x47fd0ff3:  b.w     0x47fd0ff6
   0x47fd0ff7:  str.w   r0, [r10]
   0x47fd0ffb:  movw    r0, #35992      ; 0x8c98
   0x47fd0fff:  movt    r0, #18489      ; 0x4839
   0x47fd1003:  ldr.w   pc, [r10, #24]
(gdb) p *(fragment_t*)(0x48398c98-sizeof(fragment_t))
$6 = {
  tag = 0xb6b34bba "qhC\360\001", 
  flags = 20972080, 
  size = 242, 
  prefix_size = 4 '\004', 
  fcache_extra = 6 '\006', 
  start_pc = 0x47fd0f18 "\332", <incomplete sequence \370>, 
(gdb) x/20i 0xb6b34bba
   0xb6b34bba <_IO_cleanup+182>:        ldr     r1, [r6, #4]
   0xb6b34bbc <_IO_cleanup+184>:        orr.w   r0, r3, #1
   0xb6b34bc0 <_IO_cleanup+188>:        ldr     r2, [r4, #28]
   0xb6b34bc2 <_IO_cleanup+190>:        ldr     r3, [r4, #32]
   0xb6b34bc4 <_IO_cleanup+192>:        str     r0, [r4, #0]
   0xb6b34bc6 <_IO_cleanup+194>:        subs    r3, r3, r2
   0xb6b34bc8 <_IO_cleanup+196>:        str     r1, [r4, #96]   ; 0x60
   0xb6b34bca <_IO_cleanup+198>:        str     r4, [r6, #4]
   0xb6b34bcc <_IO_cleanup+200>:        str     r2, [r4, #100]  ; 0x64
   0xb6b34bce <_IO_cleanup+202>:        str     r3, [r4, #104]  ; 0x68
   0xb6b34bd0 <_IO_cleanup+204>:        b.n     0xb6b34b7c <_IO_cleanup+120>

dcontext next_tag does match that bb fragment:
  next_tag = 0x47fd0f1d "\370\f", 
  last_exit = 0x48398c58, 
  dstack = 0x47d23000 "", 
(gdb) x/15i 0x47fd0f1d
   0x47fd0f1d:  str.w   r0, [r10, #12]
   <... opcode count increments ...>
   0x47fd0fdd:  ldr     r1, [r6, #4]
```

it's unlinked

so should have gone back to dispatch

```
(gdb) x/4wx 0x47d0d000+24
0x47d0d018:     0x47cf5921      0x47cf5981      0x47cf59cb      0x47cf5a21
(gdb) x/10i 0x47cf5921
   0x47cf5921:  str.w   r5, [r10, #12]
   0x47cf5925:  ldr.w   r5, [r10, #20]
   0x47cf5929:  stmia.w r5, {r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12}
```

doesn't make sense

```
(gdb) x/20wx 0xbe97f408 
0xbe97f408:     0x00000000      0xb6bc1760      0xb6bc1760      0x00000001
0xbe97f418:     0x00000000      0x00000000      0xb6f26000      0xb6b0bfa9
0xbe97f428:     0x00000000      0xb6b0bfd1      0xbe97f3d4      0xb6afafdf
0xbe97f438:     0xb6bc3000      0xbe97f584      0x00000004      0x0004f74d
0xbe97f448:     0x00000000      0x00000000      0x0001ba1d      0x00000000
(gdb) x/4i 0xb6bc1760
   0xb6bc1760 <__elf_set___libc_thread_subfreeres_element_arena_thread_freeres__>:      ldrtlt  r10, [r9], r1, asr #19
(gdb) x/4i 0xb6b0bfa9-4
   0xb6b0bfa5 <__run_exit_handlers+88>: subs    r3, #4
   0xb6b0bfa7 <__run_exit_handlers+90>: blx     r3
   0xb6b0bfa9 <__run_exit_handlers+92>: cmp     r5, r6
```

trying to set context within gdb to app fault context:

```
(gdb) bt
#0  0x47fd1e98 in ?? ()
#1  0xb0094532 in decode_next_pc (dcontext=<optimized out>, pc=0x0) at /home/derek/dr/git/src/core/arch/arm/decode.c:2568
#2  0xb6bc1760 in __elf_set___libc_atexit_element__IO_cleanup__ () from /lib/arm-linux-gnueabihf/libc.so.6
#3  0xb6bc1760 in __elf_set___libc_atexit_element__IO_cleanup__ () from /lib/arm-linux-gnueabihf/libc.so.6

(gdb) disas __elf_set___libc_atexit_element__IO_cleanup__
Dump of assembler code for function _IO_cleanup:
   0xb6b34b04 <+0>:     stmdb   sp!, {r4, r5, r6, r7, r8, r9, r10, lr}
   0xb6b34b08 <+4>:     movs    r0, #0
   0xb6b34b0a <+6>:     bl      0xb6b348d4 <_IO_flush_all_lockp>
   0xb6b34b0e <+10>:    ldr     r3, [pc, #268]  ; (0xb6b34c1c <_IO_cleanup+280>)
```

Summary: single app thread, running atexit handlers, enters _IO_cleanup bb
that is not linked, but somehow instead of going back to dispatch it ends
up with its PC at a non-code DR address and it gets SIGILL.  DR then fails
to translate the PC and crashes handling the SIGILL.

Well, I can add more robust code that avoids the final crash, but I'm currently stumped as to the more serious issue of how we hit the non-code in the first place.
