### ISSUE TITLE
module load event is not called for newly loaded module with custom loader

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1760]
For example, the libc is loaded into memory
```
        0xf59f6000 0xf5aec000    0xf6000        0x0 /usr/local/.../lib/libc.so
        0xf5aec000 0xf5aed000     0x1000        0x0
        0xf5aed000 0xf5af1000     0x4000    0xf6000 /usr/local/.../lib/libc.so
        0xf5af1000 0xf5af2000     0x1000    0xfa000 /usr/local/.../lib/libc.so
        0xf5af2000 0xf5af3000     0x1000    0xfb000 /usr/local/.../lib/libc.so
        0xf5af3000 0xf5af6000     0x3000    0xfc000 /usr/local/.../lib/libc.so
```
We saw the `mmap` system call:
```
system call #192==192.0 mmap2 succeeded with return value 0xf59f6000
SYS_mmap: 0xf59f6000-0xf5b00000 34
set range 0xf59f6000-0xf5b00000 => 0x0
```
and we saw the basic block event within that range:
```
in event_basic_block(tag=0xf5a0b620)
TAG  0xf5a0b620
 +0    L3              53                   push   %ebx %esp -> %esp 0xfffffffc(%esp)[4byte]
 +1    L3              83 ec 18             sub    $0x00000018 %esp -> %esp
 +4    L3              e8 a1 19 00 00       call   $0xf5a0cfca %esp -> %esp 0xfffffffc(%esp)[4byte]
END 0xf5a0b620
```
But I did not see any module event for that libc.

**Comment by zhaoqin** [comment]
In `process_mmap`, `module_is_partial_map` returns true
```
(gdb) where
#0  module_is_partial_map (base=0xf59f6000 "\177ELF\001\001\001", size=1007496, memprot=5)
    at /usr/local/.../dynamorio/core/unix/module_elf.c:282
#1  0xf729ed23 in process_mmap (dcontext=0x4f79d480, base=0xf59f6000 "\177ELF\001\001\001", size=1007496, prot=5, flags=18, map_type=0xf7358412 "mmap")
    at /usr/local/.../dynamorio/core/unix/os.c:7015
#2  0xf729fd11 in post_system_call (dcontext=0x4f79d480) at /usr/local/.../dynamorio/core/unix/os.c:7328
(gdb) p/x last_seg_end - first_seg_base
$20 = 0x10a000
(gdb) p/x size
$22 = 0xf5f88
```
so we did not add libc into the module list.
Later in `instrument_module_load_trigger`, `module_pc_lookup(pc)` returns NULL, and so the module load event will not be called.

**Comment by derekbruening** [comment]
The key here is that this app is using a custom loader and not ld-linux.so
