### ISSUE TITLE
ASSERT "module_elf.c:2092 map != NULL" and "memcache.c:345 ok" due to gold linker

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1872]
After upgrading some packages on my Fedora machine, a bunch of tests are
failing in both DR and DrM suites with two different asserts that I'm
speculating are related:

```
The following tests FAILED:
        204 - code_api|tool.drcachesim.phys (Failed)
        209 - code_api|tool.drcpusim.mmx (Failed)
        210 - code_api|tool.drcpusim.sse (Failed)
        211 - code_api|tool.drcpusim.sse2 (Failed)
        212 - code_api|tool.drcpusim.sse3 (Failed)
        213 - code_api|tool.drcpusim.ssse3 (Failed)
        214 - code_api|tool.drcpusim.sse41 (Failed)
        215 - code_api|tool.drcpusim.sse42 (Failed)
```

They all fail with this assert:

```
<Application /work/dr/nightly/run/build_debug-internal-32/suite/tests/bin/tool.mmx (19993).  Internal Error: DynamoRIO debug check failure: /work/dr/nightly/src/core/unix/module_elf.c:2092 map != NULL
```

Some DrMem tests are also failing:

```
strace_test (http://dynamorio.org/CDash/testDetails.php?test=32178&build=3505)
drsyscall_test (http://dynamorio.org/CDash/testDetails.php?test=32181&build=3505)
drfuzz_test_empty (http://dynamorio.org/CDash/testDetails.php?test=32185&build=3505)
drfuzz_test_mutator (http://dynamorio.org/CDash/testDetails.php?test=32186&build=3505)
strace_sample (http://dynamorio.org/CDash/testDetails.php?test=32187&build=3505)

<Application /work/drmemory/nightly/run/build_drmemory-dbg-32/tests/drfuzz_app_empty (26362). Unable to load client library: libdrfuzz.so.1.0
	Unable to locate library! Try adding path to LD_LIBRARY_PATH.>
<Application /work/drmemory/nightly/run/build_drmemory-dbg-32/tests/drfuzz_app_empty (26362).  Internal Error: DynamoRIO debug check failure: /work/drmemory/nightly/src/dynamorio/core/unix/memcache.c:345 ok
```

**Comment by derekbruening** [comment]
The drcpusim failures are due to the gold linker creating a zero-sized PT_LOAD segment in static executables:

```
# gdb --args bin32/drrun -loglevel 4 -msgbox_mask 14 -t drcpusim -cpu Pentium -- suite/tests/bin/tool.mmx
(gdb) bt
#0  report_dynamorio_problem (dcontext=0x0, dumpcore_flag=8, exception_addr=0x0, report_ebp=0x0, 
    fmt=0x5681a364 "DynamoRIO debug check failure: %s:%d %s\n(Error occurred @%d frags)") at /work/dr/git/src/core/utils.c:2168
#1  0x566446d4 in internal_error (file=0x568712d4 "/work/dr/git/src/core/unix/module_elf.c", line=2092, 
    expr=0x56872774 "map != NULL") at /work/dr/git/src/core/utils.c:174
#2  0x567e054d in elf_loader_map_phdrs (elf=0xff883ee0, fixed=true, map_func=0x567b4dd9 <os_map_file>, 
    unmap_func=0x567b4f0c <os_unmap_file>, prot_func=0x567b589b <os_set_protection>, reachable=false)
    at /work/dr/git/src/core/unix/module_elf.c:2092
#3  0x567d837d in privload_early_inject (sp=0xff884100, old_libdr_base=0x0, old_libdr_size=0)
    at /work/dr/git/src/core/unix/loader.c:1725
#4  0x5679bd5a in reloaded_xfer () at /work/dr/git/src/core/arch/x86/x86.asm:1191
(gdb) up 2
#2  0x567e054d in elf_loader_map_phdrs (elf=0xff883ee0, fixed=true, map_func=0x567b4dd9 <os_map_file>, 
    unmap_func=0x567b4f0c <os_unmap_file>, prot_func=0x567b589b <os_set_protection>, reachable=false)
    at /work/dr/git/src/core/unix/module_elf.c:2092
2092                ASSERT(map != NULL);
(gdb) info local
seg_end = 0x8049000 ""
file_end = 0x80480e1 ""
seg_base = 0x8049000 ""
map = 0x0
seg_size = 0
prog_hdr = 0xff883f58
lib_base = 0x8048000 "\177ELF\001\001\001"
lib_end = 0x8049000 ""
last_end = 0x8049000 ""
elf_hdr = 0xff883f04
map_base = 0x8048000 "\177ELF\001\001\001"
map_end = 0x8049000 ""
pg_offs = 4096
seg_prot = 3
i = 1
delta = 0
initial_map_size = 8192
__FUNCTION__ = "elf_loader_map_phdrs"

> cat /proc/25560/maps
08048000-08049000 r-xp 00000000 fd:09 2262552                            /work/dr/git/build_x86_dbg_tests/suite/tests/bin/tool.mmx
08049000-0804a000 ---p 00000000 00:00 0 
56561000-5689c000 r-xp 00000000 fd:09 2245711                            /work/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so.6.0
5689c000-568d8000 rw-p 0033b000 fd:09 2245711                            /work/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so.6.0
568d8000-568fc000 rw-p 00000000 00:00 0 
f7744000-f7746000 r--p 00000000 00:00 0                                  [vvar]
f7746000-f7747000 r-xp 00000000 00:00 0                                  [vdso]
ff865000-ff886000 rw-p 00000000 00:00 0                                  [stack]
```

So it's trying to map in a 0-sized segment.

I recently swapped to ld.gold and it's the gold linker that creates the
0-sized PT_LOAD entry:

```
> objdump -p suite/tests/bin/tool.mmx
suite/tests/bin/tool.mmx:     file format elf32-i386
Program Header:
    LOAD off    0x00000000 vaddr 0x08048000 paddr 0x08048000 align 2**12
         filesz 0x000000e1 memsz 0x000000e1 flags r-x
    LOAD off    0x00001000 vaddr 0x08049000 paddr 0x08049000 align 2**12
         filesz 0x00000000 memsz 0x00000000 flags rw-
    NOTE off    0x000000b4 vaddr 0x080480b4 paddr 0x080480b4 align 2**2
         filesz 0x00000024 memsz 0x00000024 flags r--
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**0
         filesz 0x00000000 memsz 0x00000000 flags rw-
```

Going back to ld.bfd and re-linking the same app and it's gone:

```
> objdump -p suite/tests/bin/tool.mmx
suite/tests/bin/tool.mmx:     file format elf32-i386
Program Header:
    LOAD off    0x00000000 vaddr 0x08048000 paddr 0x08048000 align 2**12
         filesz 0x000000c1 memsz 0x000000c1 flags r-x
    NOTE off    0x00000094 vaddr 0x08048094 paddr 0x08048094 align 2**2
         filesz 0x00000024 memsz 0x00000024 flags r--
   STACK off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**4
         filesz 0x00000000 memsz 0x00000000 flags rw-
```

**Comment by derekbruening** [comment]
The drcachesim.phys failure is due to the number of misses being very small.  The template needs to be further generalized.  It's not clear what caused this as the same binary now produces the small misses: could a kernel or ld.so change cause it?

**Comment by derekbruening** [comment]
The drmem failures are #460: our loader doesn't support DT_RUNPATH.

gold:

```
# objdump -p tests/libdrfuzz_test_empty.client.so
  RUNPATH              $ORIGIN/../../../../dr/git/exports/lib32/release:$ORIGIN/../bin/debug:$ORIGIN/../../../../dr/git/exports/ext/lib32/release
```

bfd:
```
# objdump -p /work/drmemory/build_suite/build_drmemory-dbg-32/tests/libdrfuzz_test_empty.client.so
  RPATH                $ORIGIN/../dynamorio/lib32/debug:$ORIGIN/../bin/debug:$ORIGIN/../dynamorio/ext/lib32/debug
```
