### ISSUE TITLE
CRASH release build static_noclient: dr_app_running_under_dynamorio incorrectly mangled

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1998]
Xref #975

http://dynamorio.org/CDash/testDetails.php?test=105779&build=10871

```
pre-DR init
pre-DR start
<Application /work/dr/nightly/run/build_release-external-64/suite/tests/bin/api.static_noclient (2290).  Tool internal crash at PC 0x00000000004d5c1b.  Please report this at your tool's issue tracker.  Program aborted.
Received SIGSEGV at client library pc 0x00000000004d5c1b in thread 2290
Base: 0x0000000000400000
```

```
Program received signal SIGSEGV, Segmentation fault.
instr_encode_arch (dcontext=dcontext@entry=0x550a6780, instr=instr@entry=0x5511d998, copy_pc=copy_pc@entry=0x0, 
    final_pc=final_pc@entry=0x0, check_reachable=check_reachable@entry=true, has_instr_opnds=has_instr_opnds@entry=0x0)
    at /work/dr/git/src/core/arch/x86/encode.c:2501
2501            case SEG_GS: *field_ptr = 0x65; break;
(gdb) bt
#0  instr_encode_arch (dcontext=dcontext@entry=0x550a6780, instr=instr@entry=0x5511d998, copy_pc=copy_pc@entry=0x0, 
    final_pc=final_pc@entry=0x0, check_reachable=check_reachable@entry=true, has_instr_opnds=has_instr_opnds@entry=0x0)
    at /work/dr/git/src/core/arch/x86/encode.c:2501
#1  0x00000000004cf44e in instr_encode_to_copy (dcontext=dcontext@entry=0x550a6780, instr=instr@entry=0x5511d998, 
    copy_pc=copy_pc@entry=0x0, final_pc=final_pc@entry=0x0) at /work/dr/git/src/core/arch/encode_shared.c:120
#2  0x00000000004cf458 in instr_encode (dcontext=dcontext@entry=0x550a6780, instr=instr@entry=0x5511d998, pc=pc@entry=0x0)
    at /work/dr/git/src/core/arch/encode_shared.c:127
#3  0x0000000000459635 in set_linkstub_fields (dcontext=dcontext@entry=0x550a6780, f=f@entry=0x550f7108, 
    ilist=ilist@entry=0x5511de50, num_direct_stubs=num_direct_stubs@entry=0, num_indirect_stubs=num_indirect_stubs@entry=1, 
    emit=emit@entry=true) at /work/dr/git/src/core/emit.c:371
#4  0x0000000000459ad7 in emit_fragment_common (dcontext=dcontext@entry=0x550a6780, 
    tag=tag@entry=0x4f5b5b <dr_app_running_under_dynamorio> "\270", ilist=0x5511de50, flags=16777216, vmlist=0x550f7050, 
    link_fragment=link_fragment@entry=true, add_to_htable=true, replace_fragment=0x0) at /work/dr/git/src/core/emit.c:682
#5  0x000000000045a735 in emit_fragment_ex (dcontext=dcontext@entry=0x550a6780, 
    tag=tag@entry=0x4f5b5b <dr_app_running_under_dynamorio> "\270", ilist=<optimized out>, flags=<optimized out>, 
    vmlist=<optimized out>, link=link@entry=true, visible=true) at /work/dr/git/src/core/emit.c:1011
#6  0x00000000004e34ea in build_basic_block_fragment (dcontext=dcontext@entry=0x550a6780, start=<optimized out>, 
    initial_flags=initial_flags@entry=0, link=link@entry=true, visible=visible@entry=true, for_trace=for_trace@entry=false, 
```

The other static tests all pass.

```
(gdb) p /x *(fragment_t*)0x550f7108
$16 = {
  tag = 0x4f5b5b, 
  flags = 0x1000000, 
  size = 0x12, 
  prefix_size = 0x0, 
  fcache_extra = 0xa, 
  start_pc = 0x550c5024, 
 ```

It's encoding at 0 for the 2nd instr, but I think the 1st one failed and
set pc to 0:

```
                pc = instr_encode(dcontext, inst, pc);
                ASSERT(pc != NULL);
```

Esp since there's nothing in the fragment:

```
(gdb) x/10i 0x4f5b5b
   0x4f5b5b <dr_app_running_under_dynamorio>:   mov    $0x0,%eax
   0x4f5b60 <dr_app_running_under_dynamorio+5>: retq   
(gdb) x/10i 0x550c5024
   0x550c5024:  add    %al,(%rax)
   0x550c5026:  add    %al,(%rax)

(gdb) p /x *((instrlist_t*)0x5511de50)->first
$12 = {
  flags = 0x10000, 
  length = 0x5, 
  bytes = 0x4f5b5b, 
  translation = 0x0, 
  opcode = 0x1, 
  rip_rel_pos = 0x0, 
  num_dsts = 0x0, 
  num_srcs = 0x0, 
  next = 0x5511d998

    INSTR_OPERANDS_VALID        = 0x00010000,
```

2nd instr is a meta mov, looks like spill of ecx.

So why does the 1st instr have an undecoded opcode OP_UNDECODED, no
operands, yet its flags claims it has operands?

It's release build w/ no client bb event so it must be doing level 0
instrs, and the hacky dr_app_running_under_dynamorio mangling messes up?

**Comment by derekbruening** [comment]
This was fixed in d494a0e7d123c701bafc4f119946e433f07e4cea
