### ISSUE TITLE
ASSERT "not at syscall" during detach

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2026]
Testing dr_app_stop_and_cleanup() on a larger app hits this assert during the detach:

```
Internal Error: DynamoRIO debug check failure: core/fragment.c:5833 !DYNAMO_OPTION(syscalls_synch_flush) || !get_at_syscall(dcontext)
(Error occurred @163603 frags)
```

**Comment by derekbruening** [comment]
```
#6  0x0000000002275152 in internal_error (file=0x2c60b06 <.L.str.22> "dynamorio/trunk/core/fragment.c", line=5833, 
    expr=0x2c64bd4 <.L.str.259> "!DYNAMO_OPTION(syscalls_synch_flush) || !get_at_syscall(dcontext)") at dynamorio/trunk/core/utils.c:174
#7  0x0000000002088244 in enter_couldbelinking (dcontext=0x530b4640, was_I_flushed=0x0, cache_transition=0 '\000')
    at dynamorio/trunk/core/fragment.c:5833
#8  0x000000000214e782 in trace_abort (dcontext=0x530b4640) at dynamorio/trunk/core/monitor.c:2388
#9  0x000000000214e6f5 in trace_abort_and_delete (dcontext=0x530b4640) at dynamorio/trunk/core/monitor.c:326
#10 0x0000000001f90b41 in dynamo_thread_exit_pre_client (dcontext=0x530b4640, id=141860) at dynamorio/trunk/core/dynamo.c:2300
#11 0x0000000001f90f3e in dynamo_thread_exit_common (dcontext=0x530b4640, id=141860, other_thread=1 '\001')
    at dynamorio/trunk/core/dynamo.c:2406
#12 0x0000000001f8dd01 in dynamo_other_thread_exit (tr=0x530b4b70) at dynamorio/trunk/core/dynamo.c:2549
#13 0x00000000022106b8 in detach_on_permanent_stack (internal=1 '\001', do_cleanup=1 '\001') at dynamorio/trunk/core/synch.c:2081
#14 0x0000000001f9322f in dr_app_stop_and_cleanup () at dynamorio/trunk/core/dynamo.c:2654
```

I believe this should just be suppressed for doing_detach as everyone is suspended.
