### ISSUE TITLE
CRASH tool.drcacheoff.burst_threads debug build test on Travis

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2054]
Travis is still showing a crash in the burst_threads test.  Like the
original Travis crash listed for #2049, it doesn't have a full DR crash
report.  Plus, it's debug build.  The clean call race in #2049 has a full
DR crash report and is release-only (with my compiler anyway).  I guess all
the Travis crashes in this test are something different from the clean call
race of #2049: hence this separate issue.  Something early on, before the
DR crash handler is set up.

```
https://travis-ci.org/DynamoRIO/dynamorio/jobs/172929230
216: Test command: /usr/bin/cmake "-D" "precmd=/usr/bin/cmake@-E@remove_directory@drmemtrace.tool.drcacheoff.burst_threads.*.dir" "-D" "cmd=/home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/clients/bin64/tool.drcacheoff.burst_threads" "-D" "postcmd=/home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/clients/bin64/drcachesim@-indir@drmemtrace.tool.drcacheoff.burst_threads.*.dir" "-D" "cmp=/home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/offline-burst_threads.expect" "-P" "/home/travis/build/DynamoRIO/dynamorio/suite/tests/runmulti.cmake"
216: Test timeout computed to be: 600
216: CMake Error at /home/travis/build/DynamoRIO/dynamorio/suite/tests/runmulti.cmake:86 (message):
216:   ***
216:   /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/clients/bin64/tool.drcacheoff.burst_threads
216:   failed (Segmentation fault): pre-DR init
216: 
216:   pre-DR start
216: 
216:   ***
216: 
216: 
216: 
215/247 Test #216: code_api|tool.drcacheoff.burst_threads ...........................***Failed    0.90 sec
```

**Comment by derekbruening** [comment]
Qin managed to reproduce this in a VM only running 3 parallel shells 100x each and got one core dump 

```
(gdb) bt
#0  0x00000000006d0893 in signal_thread_inherit (dcontext=0x46c2ea00, clone_record=0x7fa7d4089480)
    at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/unix/signal.c:833
#1  0x00000000006d143c in share_siginfo_after_take_over (dcontext=0x46c2ea00, takeover_dc=0x46c2ea00)
    at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/unix/signal.c:1058
#2  0x00000000006ceec1 in os_thread_take_over_secondary (dcontext=0x46c2ea00)
    at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/unix/os.c:9432
#3  0x00000000006a0253 in dynamo_start (mc=0x7fa7d4089c00) at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/arch/x86_code.c:98
#4  0x0000000000478bc6 in dr_app_start_helper (mc=0x7fa7d4089c00) at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/dynamo.c:2631
#5  0x00000000006a0dec in dr_app_start () at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/arch/x86/x86.asm:515
#6  0x00007fa7d644e1c0 in ?? ()
#7  0x00007fa7d644f9d0 in ?? ()
#8  0x00007fa7d4089ed0 in ?? ()
#9  0x00007fa7d4089eb0 in ?? ()
#10 0x0000000000000000 in ?? ()
(gdb) p *clone_record
Attempt to dereference a generic pointer.
(gdb) p *(clone_record_t*)clone_record
$1 = {
  dstack = 0x300000b400 <error: Cannot access memory at address 0x300000b400>, 
  app_thread_xsp = 8021877, 
  continuation_pc = 0x7fa7d4089600 "", 
  caller_id = 46080, 
  clone_sysnum = 56, 
  clone_flags = 4001536, 
  info = {
    app_sigaction = 0x0, 
    fully_initialized = false, 
    shared_app_sigaction = true, 
    shared_lock = 0x46c316f8, 
    shared_refcount = 0x46c316f0, 
    we_intercept = 0x0, 
    shared_itimer = true, 
    shared_itimer_lock = 0x46c31788, 
    shared_itimer_refcount = 0x46c31778, 
    shared_itimer_underDR = 0x46c31780, 
    itimer = 0x0, 
(gdb) up 2
#2  0x00000000006ceec1 in os_thread_take_over_secondary (dcontext=0x46c2ea00)
    at /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/unix/os.c:9432
9432    /home/drfuzz/SecDev16/DynamoRIO/dynamorio/core/unix/os.c: No such file or directory.
(gdb) p num_threads
$4 = 2
(gdb) p *list[0]
$6 = {
  id = 46080, 
  pid = 46075, 
  execve = false, 
  num = 1, 
  under_dynamo_control = true, 
  dcontext = 0x46c2ea00, 
  next = 0x0
}
(gdb) p *list[1]
$7 = {
  id = 46075, 
  pid = 46075, 
  execve = false, 
  num = 0, 
  under_dynamo_control = true, 
  dcontext = 0x46b8c140, 
  next = 0x0
}
```

So the code from i#2034 has a bad assumption that the first thread is list[0].
