### ISSUE TITLE
ASSERT at -loglevel 2: kstats "stop not matching TOS"

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2098]
After #2089 in 184dd8b, -loglevel 2 for 32-bit api.startstop hits an assert:

<Application /work/dr/build_suite/build_debug-internal-32/suite/tests/bin/api.startstop (1102).  Internal Error: DynamoRIO debug check failure: /work/dr/git/src/core/utils.c:1890 ks->node[ks->depth - 1].var == pv && "stop not matching TOS"

The KSTOP_NOT_PROPAGATED complains:

```
(gdb) p get_thread_private_dcontext()->thread_kstats->stack_kstats
$6 = {
  depth = 2, 
  last_start_time = 3475043799516650, 
  last_end_time = 3475043799516650, 
  node = {{
      var = 0xabababab, 
      self_time = 12370169555311111083, 
      subpath_time = 12370169555311111083, 
      outlier_time = 12370169555311111083
    }, {
      var = 0x55225f6c, 
      self_time = 0, 
      subpath_time = 2861110, 
      outlier_time = 0
    }, {
      var = 0x55226518, 
      self_time = 18505, 
      subpath_time = 0, 
      outlier_time = 0
    }, {
      var = 0x55226518, 
      self_time = 6471, 
      subpath_time = 0, 
      outlier_time = 0
    }, {

(gdb) p &get_thread_private_dcontext()->thread_kstats->vars_kstats.logging
$11 = (kstat_variable_t *) 0x55226518
(gdb) p &get_thread_private_dcontext()->thread_kstats->vars_kstats.thread_measured
$13 = (kstat_variable_t *) 0x55225f6c
```

So get_thread_private_dcontext()->thread_kstats->stack_kstats->node[1].var
is thread_measured instead of logging.

-no_safe_read_tls_init never hits this assert: works fine at -loglevel 2.

It looks like the problem is that we're in the middle of the 2-part swap
and that leaves the DR TLS in a bad state: we've set the GDT but not the
segment register.

**Comment by derekbruening** [comment]
But later I see the same assert on the thread exit path:

```
#5  0x710e6271 in internal_error (file=0x712d0627 "/work/dr/git/src/core/stats.c", line=369, 
    expr=0x712d0648 "ks->node[ks->depth - 1].var == pv && \"stop not matching TOS\"") at /work/dr/git/src/core/utils.c:174
#6  0x7115564f in kstat_thread_exit (dcontext=0x479b5800) at /work/dr/git/src/core/stats.c:369
#7  0x7106caea in dynamo_thread_exit_common (dcontext=0x479b5800, id=5567, other_thread=false) at /work/dr/git/src/core/dynamo.c:2463
#8  0x7106cc4f in dynamo_thread_exit () at /work/dr/git/src/core/dynamo.c:2540
#9  0x712402e0 in cat_thread_only () at /work/dr/git/src/core/arch/x86/x86.asm:630

Thread KSTAT stack:
[2] 0x47a54758 dispatch_num_exits
[1] 0x47a5473c thread_measured
```

The problem is that we run through dispatch and go back native for this
sysenter hook with get_thread_private_dcontext() as NULL, so most kstats are
nops, *except* this one:

```
    KSTART_DC(dcontext, dispatch_num_exits);
```

Solution is to add _DC to the KSTOP for sysenter.
