### ISSUE TITLE
Signal tests failure in clang build due to stack misalignment

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#2330]
Project: DynamoRIO
Site: X64.Ubuntu1404.Clang37.CAM
Build Name: debug-internal-32
Build Time: 2017-04-05T18:00:22 MDT
Type: Nightly
Tests failing: 17

*Tests failing* (first 5)
code_api|linux.signal0011 (http://dynamorio.org/CDash/testDetails.php?test=236317&build=21285)
code_api|linux.signal0001 (http://dynamorio.org/CDash/testDetails.php?test=236318&build=21285)
code_api|linux.signal1001 (http://dynamorio.org/CDash/testDetails.php?test=236319&build=21285)
code_api|linux.signal0101 (http://dynamorio.org/CDash/testDetails.php?test=236320&build=21285)
code_api|linux.signal0111 (http://dynamorio.org/CDash/testDetails.php?test=236321&build=21285)

Trace test linux.signal0001
A segfault happens in a `memset` called from `set_actual_itimer`
```
(gdb) where
#0  set_actual_itimer (dcontext=0xef7d9bc0, which=1, info=0xef835128, enable=false) at DynamoRIO/nightly/src/core/unix/signal.c:6085
#1  0x56bd71b2 in itimer_new_settings (dcontext=0xef7d9bc0, which=1, app_changed=true) at DynamoRIO/nightly/src/core/unix/signal.c:6120
#2  0x56bd8149 in handle_pre_setitimer (dcontext=0xef7d9bc0, which=1, new_timer=0xffe58668, prev_timer=0x0) at DynamoRIO/nightly/src/core/unix/signal.c:6404
#3  0x56ba6445 in pre_system_call (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/unix/os.c:7214
#4  0x56806c82 in handle_system_call (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/dispatch.c:1986
#5  0x56803497 in dispatch_enter_dynamorio (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/dispatch.c:880
#6  0x568000a7 in dispatch (dcontext=0xef7d9bc0) at 
DynamoRIO/nightly/src/core/dispatch.c:164
(gdb) x/2i $pc
=> 0x56bc1621 <set_actual_itimer+993>:  movaps %xmm0,-0x38(%ebp)
   0x56bc1625 <set_actual_itimer+997>:  mov    -0x14(%ebp),%eax
(gdb) p/x $ebp
$6 = 0xef832174
```
So it is clear a stack misalignment for `movaps` instruction.

**Comment by zhaoqin** [comment]
Check stack pointers:
```
(gdb) p/x $ebp
$6 = 0xef832174
(gdb) up
#1  0x56bd71b2 in itimer_new_settings (dcontext=0xef7d9bc0, which=1, app_changed=true) at DynamoRIO/nightly/src/core/unix/signal.c:6120
(gdb) p $ebp
$7 = (void *) 0xef832234
(gdb) up
#2  0x56bd8149 in handle_pre_setitimer (dcontext=0xef7d9bc0, which=1, new_timer=0xffe58668, prev_timer=0x0) at DynamoRIO/nightly/src/core/unix/signal.c:6404
(gdb) p $ebp
$8 = (void *) 0xef8322d4
(gdb) up
#3  0x56ba6445 in pre_system_call (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/unix/os.c:7214
(gdb) p $ebp
$9 = (void *) 0xef832b04
(gdb) up
#4  0x56806c82 in handle_system_call (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/dispatch.c:1986
(gdb) p $ebp
$10 = (void *) 0xef832ca4
(gdb) up
#5  0x56803497 in dispatch_enter_dynamorio (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/dispatch.c:880
(gdb) p $ebp
$11 = (void *) 0xef832e84
(gdb) up
#6  0x568000a7 in dispatch (dcontext=0xef7d9bc0) at DynamoRIO/nightly/src/core/dispatch.c:164
(gdb) p $ebp
$12 = (void *) 0xef832ff4
```

**Comment by derekbruening** [comment]
I'm seeing crashes running just about anything on Mac.  I don't think
anything was upgraded all that recently but I have not run anything here in
a few months, maybe not since this xcode upgrade to 8.0:

```
$ /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The crash is stack alignment and probably the same as this issue?

```
Fragment 390, tag 0x96c9d2d0, flags 0x1000630, shared, size 81:
  0x4c5dba60  83 ec 64             sub    $0x00000064 %esp -> %esp
  0x4c5dba63  89 44 24 54          mov    %eax -> 0x54(%esp)[4byte]
  0x4c5dba67  8b 44 24 68          mov    0x68(%esp)[4byte] -> %eax
  0x4c5dba6b  89 44 24 60          mov    %eax -> 0x60(%esp)[4byte]
  0x4c5dba6f  89 6c 24 68          mov    %ebp -> 0x68(%esp)[4byte]
  0x4c5dba73  89 e5                mov    %esp -> %ebp
  0x4c5dba75  83 c5 68             add    $0x00000068 %ebp -> %ebp
  0x4c5dba78  89 4c 24 58          mov    %ecx -> 0x58(%esp)[4byte]
  0x4c5dba7c  89 54 24 5c          mov    %edx -> 0x5c(%esp)[4byte]
  0x4c5dba80  66 0f 7f 44 24 10    movdqa %xmm0 -> 0x10(%esp)[16byte]
  0x4c5dba86  66 0f 7f 4c 24 20    movdqa %xmm1 -> 0x20(%esp)[16byte]
  0x4c5dba8c  66 0f 7f 54 24 30    movdqa %xmm2 -> 0x30(%esp)[16byte]
  0x4c5dba92  66 0f 7f 5c 24 40    movdqa %xmm3 -> 0x40(%esp)[16byte]
  0x4c5dba98  8b 44 24 64          mov    0x64(%esp)[4byte] -> %eax
  0x4c5dba9c  89 04 24             mov    %eax -> (%esp)[4byte]
  0x4c5dba9f  8b 44 24 60          mov    0x60(%esp)[4byte] -> %eax
  0x4c5dbaa3  89 44 24 04          mov    %eax -> 0x04(%esp)[4byte]
  0x4c5dbaa7  68 1c d3 c9 96       push   $0x96c9d31c %esp -> %esp 0xfffffffc(%esp)[4byte]
  0x4c5dbaac  e9 4c e5 01 00       jmp    $0x4c5f9ffd
  -------- exit stub 0: -------- <target: 0x96c9eba6> type: call
  0x4c5f9ffd  67 64 a3 00 00       addr16 mov    %eax -> %fs:0x00[4byte]
  0x4c5fa002  b8 38 c2 66 4c       mov    $0x4c66c238 -> %eax
  0x4c5fa007  e9 f4 7e fd ff       jmp    $0x4c5d1f00 <fcache_return> 

priv_mcontext_t @0x4c5bd4c0
        xax = 0xa2f176b0
        xbx = 0xbff92a54
        xcx = 0xbff9292c
        xdx = 0xa2f170fc
        xsi = 0x00070e2d
        xdi = 0xbff928f8
        xbp = 0xbff92920
        xsp = 0xbff928ec
Entry into F390(0x96c9d2d0).0x4c5dba60 (shared)
master_signal_handler: sig=11, retaddr=0xffffffff
siginfo: sig = 11, pid = 0, status = 0, errno = 0, si_code = 0
        xdi=0xbff928f8
        xsi=0x00070e2d
        xbp=0xbff928f0
        xsp=0xbff92888
        xbx=0xbff92a54
        xdx=0xa2f170fc
        xcx=0xbff9292c
        xax=0x0000011e
        xip=0x4c5dba80
        eflags=0x00010296
```

**Comment by derekbruening** [comment]
Xref #2024
