### ISSUE TITLE
many tests failing on Travis after some kind of Travis upgrade

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2634]
Nearly every test is failing for 32-bit, and a bunch are timing out on 64-bit.  For 32-bit we'll have to run with -VV to try and see what's going on but from those tests that do happen to print their output it looks like it's all blank so this will not be easy to figure out unless we can repro locally.

**Comment by derekbruening** [comment]
Xref #2632

**Comment by derekbruening** [comment]
https://travis-ci.org/DynamoRIO/dynamorio/builds/273741461

32-bit:

```
11% tests passed, 247 tests failed out of 279

Total Test time (real) = 2595.86 sec

The following tests FAILED:
	  5 - code_api|common.broadfun (Failed)
	  6 - code_api|common.logstderr (Failed)
	  8 - code_api|common.decode-bad (Failed)
	  9 - code_api|common.eflags (Failed)
	 10 - code_api|common.floatpc (Failed)
	 11 - code_api|common.floatpc_xl8all (Failed)
	 12 - code_api|common.getretaddr (Failed)
	 20 - code_api|common.segfault (Failed)
	 21 - code_api|client.memval-test (Failed)
	 22 - code_api|linux.clone (Failed)
	 23 - code_api|linux.clone-pie (Failed)
	 24 - code_api|linux.execve-null (Failed)
	 25 - code_api|linux.child-blacklist (Failed)
	 26 - code_api|linux.child-whitelist (Failed)
	 27 - code_api|linux.execve-rec (Failed)
	 28 - code_api|linux.exit (Failed)
	 29 - code_api|linux.fork (Failed)
	 30 - code_api|linux.fork-sleep (Failed)
	 31 - code_api|linux.fork-MSR (Failed)
	 33 - code_api|linux.longjmp (Failed)
	 34 - code_api|linux.prctl (Failed)
	 35 - code_api|linux.mmap (Failed)
	 36 - code_api|linux.signal0000 (Failed)
	 37 - code_api|linux.signal0001 (Failed)
	 38 - code_api|linux.signal0010 (Failed)
	 39 - code_api|linux.signal0011 (Failed)
	 40 - code_api|linux.signal0100 (Failed)
	 41 - code_api|linux.signal0101 (Failed)
	 42 - code_api|linux.signal0110 (Failed)
	 43 - code_api|linux.signal0111 (Failed)
	 44 - code_api|linux.signal1000 (Failed)
	 45 - code_api|linux.signal1001 (Failed)
	 46 - code_api|linux.signal1010 (Failed)
	 47 - code_api|linux.signal1011 (Failed)
	 48 - code_api|linux.signal1100 (Failed)
	 49 - code_api|linux.signal1101 (Failed)
	 50 - code_api|linux.signal1110 (Failed)
	 51 - code_api|linux.signal1111 (Failed)
	 52 - code_api|linux.sigplain000 (Failed)
	 53 - code_api|linux.sigplain001 (Failed)
	 54 - code_api|linux.sigplain010 (Failed)
	 55 - code_api|linux.sigplain011 (Failed)
	 56 - code_api|linux.sigplain100 (Failed)
	 57 - code_api|linux.sigplain101 (Failed)
	 58 - code_api|linux.sigplain110 (Failed)
	 59 - code_api|linux.sigplain111 (Failed)
	 60 - code_api|linux.sigaction (Failed)
	 61 - code_api|linux.sigaction_nosignals (Failed)
	 62 - code_api|linux.sigcontext (Failed)
	 63 - code_api|linux.thread (Failed)
	 64 - code_api|linux.threadexit (Failed)
	 65 - code_api|linux.threadexit2 (Failed)
	 66 - code_api|linux.signalfd (Failed)
	 67 - code_api|linux.alarm (Failed)
	 68 - code_api|linux.signal_race (Failed)
	 69 - code_api|linux.signal_racesys (Failed)
	 70 - code_api|linux.eintr (Failed)
	 71 - code_api|linux.eintr-noinline (Failed)
	 72 - code_api|linux.sigsuspend (Failed)
	 73 - code_api|linux.signest (Failed)
	 74 - code_api|linux.app_tls (Failed)
	 75 - code_api|linux.readlink (Failed)
	 76 - code_api|linux.fib-conflict (Failed)
	 77 - code_api|linux.fib-conflict-early (Failed)
	 78 - code_api|linux.fib-static (Failed)
	 79 - code_api|linux.fib-pie (Failed)
	 80 - code_api|linux.vfork (Failed)
	 81 - code_api|linux.thread-reset (Failed)
	 82 - code_api|linux.clone-reset (Failed)
	 83 - code_api|pthreads.pthreads (Failed)
	 85 - code_api|pthreads.ptsig_FLAKY (Failed)
	 86 - code_api|pthreads.pthreads_fork_FLAKY (Failed)
	 87 - code_api|security-linux.stacktest (Failed)
	 88 - code_api|security-linux.trampoline (Failed)
	 89 - code_api|linux.reset (Timeout)
	 90 - code_api|linux.freeze_FLAKY (Timeout)
	 91 - code_api|linux.persist_FLAKY (Timeout)
	 92 - code_api|linux.persist-use_FLAKY (Timeout)
	 93 - code_api|security-common.codemod (Failed)
	 94 - code_api|security-common.decode-bad-stack (Failed)
	 95 - code_api|security-common.retexisting (Failed)
	 96 - code_api|security-common.ret_noncall_trace (Failed)
	 97 - code_api|security-common.retnonexisting (Failed)
	 98 - code_api|security-common.selfmod2 (Failed)
	 99 - code_api|security-common.selfmod-big (Failed)
	100 - code_api|security-common.selfmod (Failed)
	101 - code_api|security-common.vbjmp-rac-test (Failed)
	102 - code_api|security-common.TestAllocWE (Failed)
	103 - code_api|security-common.TestMemProtChg_FLAKY (Failed)
	104 - code_api|client.call-retarget (Failed)
	105 - code_api|client.abort (Failed)
	106 - code_api|client.crashmsg (Failed)
	107 - code_api|client.stack-overflow (Failed)
	108 - code_api|client.modules (Failed)
	109 - code_api|client.alloc (Failed)
	110 - code_api|client.cleancall (Failed)
	111 - code_api|client.cleancall.prof-pcs (Failed)
	112 - code_api|client.cleancall.prof-pcs.thread-private (Failed)
	113 - code_api|client.count-ctis (Failed)
	114 - code_api|client.count-ctis-noopt (Failed)
	115 - code_api|client.syscall (Failed)
	116 - code_api|client.count-bbs (Failed)
	117 - code_api|client.cleancallparams (Failed)
	118 - code_api|client.app_inscount (Failed)
	119 - code_api|client.exception (Failed)
	120 - code_api|client.annotation-concurrency (Failed)
	121 - code_api|client.annotation-concurrency.full-decode (Failed)
	122 - code_api|client.annotation-concurrency.full-decode.tiny-bb (Failed)
	123 - code_api|client.annotation-concurrency.bb-truncate-1 (Failed)
	124 - code_api|client.annotation-concurrency.bb-truncate-2 (Failed)
	125 - code_api|client.annotation-concurrency.prof-pcs (Failed)
	126 - code_api|client.annotation-concurrency.prof-pcs.thread-private (Failed)
	127 - code_api|client.annotation-concurrency-opt (Failed)
	128 - code_api|client.annotation-concurrency-opt.full-decode (Failed)
	129 - code_api|client.annotation-detection (Failed)
	130 - code_api|client.annotation-detection.full-decode (Failed)
	131 - code_api|client.annotation-detection.full-decode.tiny-bb (Failed)
	132 - code_api|client.annotation-detection.bb-truncate-1 (Failed)
	133 - code_api|client.annotation-detection.bb-truncate-2 (Failed)
	134 - code_api|client.annotation-detection-opt (Failed)
	135 - code_api|client.partial_module_map (Failed)
	136 - code_api|client.mbr_instrumentation_segment (Failed)
	137 - code_api|client.segfault (Failed)
	138 - code_api|client.execfault (Failed)
	139 - code_api|client.vg-annot (Failed)
	140 - code_api|client.vg-annot.full-decode (Failed)
	141 - code_api|client.vg-annot.full-decode.tiny-bb (Failed)
	142 - code_api|client.vg-annot.bb-truncate-1 (Failed)
	143 - code_api|client.vg-annot.bb-truncate-2 (Failed)
	144 - code_api|client.vg-annot-opt (Failed)
	145 - code_api|client.vg-annot-opt.full-decode (Failed)
	146 - code_api|client.vg-annot-opt.full-decode.tiny-bb (Failed)
	147 - code_api|client.vg-annot-opt.bb-truncate (Failed)
	148 - code_api|client.events (Failed)
	149 - code_api|client.events_cpp (Failed)
	150 - code_api|client.nudge_test (Timeout)
	151 - code_api|client.timer (Failed)
	152 - code_api|client.syscall-mod (Failed)
	153 - code_api|client.signal (Failed)
	154 - code_api|client.cbr-retarget (Failed)
	155 - code_api|client.file_io (Failed)
	156 - code_api|client.flush (Failed)
	157 - code_api|client.thread (Failed)
	158 - code_api|client.strace (Failed)
	159 - code_api|client.truncate (Failed)
	160 - code_api|client.dr_options (Failed)
	161 - code_api|client.unregister (Failed)
	162 - code_api|client.inline (Failed)
	163 - code_api|client.cleancall-opt-1 (Failed)
	164 - code_api|client.null_instrument (Failed)
	165 - code_api|client.large_options (Failed)
	166 - code_api|client.option_parse (Failed)
	167 - code_api|client.thread_exit_xl8 (Failed)
	168 - code_api|client.drcontainers-test (Failed)
	169 - code_api|client.drmgr-test (Failed)
	170 - code_api|client.drx_buf-test (Failed)
	171 - code_api|client.drreg-test (Failed)
	172 - code_api|client.drreg-flow (Failed)
	173 - code_api|client.drreg-cross (Failed)
	174 - code_api|client.drx-test (Failed)
	175 - code_api|client.drxmgr-test (Failed)
	176 - code_api|client.drwrap-test (Failed)
	177 - code_api|client.drwrap-test-callconv (Failed)
	178 - code_api|client.drsyms-test (Failed)
	179 - code_api|client.drutil-test (Failed)
	180 - code_api|client.drmodtrack-test (Failed)
	181 - code_api|client.pcache (Failed)
	182 - code_api|client.pcache-use (Failed)
	183 - code_api|client.fcache_shift (Failed)
	184 - code_api|client.reachability (Failed)
	185 - code_api|client.nudge_ex (Failed)
	186 - code_api|client.retaddr (Failed)
	187 - code_api|client.destructor (Failed)
	188 - code_api|sample.bbbuf (Failed)
	189 - code_api|sample.bbcount (Failed)
	190 - code_api|sample.bbsize (Failed)
	191 - code_api|sample.div (Failed)
	192 - code_api|sample.empty (Failed)
	193 - code_api|sample.memtrace_simple (Failed)
	194 - code_api|sample.memval_simple (Failed)
	195 - code_api|sample.instrace_simple (Failed)
	196 - code_api|sample.cbr (Failed)
	197 - code_api|sample.countcalls (Failed)
	198 - code_api|sample.inc2add (Failed)
	199 - code_api|sample.memtrace_x86_binary (Failed)
	200 - code_api|sample.memtrace_x86_text (Failed)
	201 - code_api|sample.instrace_x86_binary (Failed)
	202 - code_api|sample.instrace_x86_text (Failed)
	203 - code_api|sample.prefetch (Failed)
	204 - code_api|sample.ssljack (Failed)
	205 - code_api|sample.modxfer (Failed)
	206 - code_api|sample.modxfer_app2lib (Failed)
	207 - code_api|sample.instrcalls (Failed)
	208 - code_api|sample.cbrtrace (Failed)
	209 - code_api|sample.wrap (Failed)
	210 - code_api|sample.signal (Failed)
	211 - code_api|sample.syscall (Failed)
	212 - code_api|sample.inline (Failed)
	213 - code_api|sample.inscount (Failed)
	214 - code_api|sample.inscount.cleancall (Failed)
	215 - code_api|sample.inscount.prof-pcs.cleancall (Failed)
	216 - code_api|sample.inscount.prof-pcs.thread-private.cleancall (Failed)
	217 - code_api|sample.opcodes (Failed)
	218 - code_api|sample.stl_test (Failed)
	219 - code_api|tool.drcov.fib (Failed)
	220 - code_api|tool.drcachesim.simple (Failed)
	221 - code_api|tool.drcachesim.TLB-simple (Failed)
	222 - code_api|tool.drcachesim.phys (Failed)
	223 - code_api|tool.drcachesim.filter (Failed)
	224 - code_api|tool.drcachesim.threads (Timeout)
	225 - code_api|tool.drcachesim.TLB-threads (Timeout)
	226 - code_api|tool.drcachesim.multiproc (Failed)
	227 - code_api|tool.histogram (Failed)
	228 - code_api|tool.reuse (Failed)
	229 - code_api|tool.drcacheoff.simple (Failed)
	230 - code_api|tool.drcacheoff.multiproc (Failed)
	231 - code_api|tool.drcacheoff.filter (Failed)
	236 - code_api|tool.drcacheoff.burst_threads (Timeout)
	237 - code_api|tool.raw2trace.simple (Failed)
	239 - code_api|tool.histogram.offline (Failed)
	240 - code_api|tool.drcpusim.simple (Failed)
	241 - code_api|tool.drcpusim.mmx (Failed)
	242 - code_api|tool.drcpusim.sse (Failed)
	243 - code_api|tool.drcpusim.sse2 (Failed)
	244 - code_api|tool.drcpusim.sse3 (Failed)
	245 - code_api|tool.drcpusim.ssse3 (Failed)
	246 - code_api|tool.drcpusim.sse41 (Failed)
	247 - code_api|tool.drcpusim.sse42 (Failed)
	248 - code_api|tool.drcpusim.cpuid-Klamath (Failed)
	249 - code_api|tool.drcpusim.cpuid-Deschutes (Failed)
	250 - code_api|tool.drcpusim.cpuid-Pentium3 (Failed)
	251 - code_api|tool.drcpusim.cpuid-Banias (Failed)
	252 - code_api|tool.drcpusim.cpuid-Prescott (Failed)
	253 - code_api|tool.drcpusim.cpuid-Presler (Failed)
	254 - code_api|tool.drcpusim.cpuid-Merom (Failed)
	255 - code_api|tool.drcpusim.cpuid-Penryn (Failed)
	256 - code_api|tool.drcpusim.cpuid-Westmere (Failed)
	257 - code_api|tool.drcpusim.cpuid-Nehalem (Failed)
	262 - code_api|api.detach (Failed)
	263 - code_api|api.detach_spawn (Failed)
	271 - code_api|api.static_signal (Failed)
	273 - code_api|api.static_sideline_FLAKY (Failed)
	274 - code_api,opt_memory|client.events (Failed)
	275 - code_api,opt_speed|client.events (Failed)
	276 - code_api,thread_private|client.events (Failed)
	277 - code_api,disable_traces|client.events (Failed)
	278 - code_api,thread_private,disable_traces|client.events (Failed)
```

64-bit:

```
debug-internal-64: 265 tests passed, **** 10 tests failed, of which 1 were flaky, but ignoring 0 for i: ****
	linux.execve32 
	linux.execve64 
	code_api|linux.threadexit2 
	code_api|security-common.selfmod-big 
	code_api|client.partial_module_map 
	code_api|api.detach 
	code_api|api.detach_spawn 
	code_api|api.static_signal 
	code_api|api.static_sideline_FLAKY 
	code_api|tool.drcacheoff.burst_threads 
```

**Comment by derekbruening** [comment]
Travis:
```
$ uname -a
Linux testing-gce-cef920dc-bfb6-4b89-bb39-d25243a946c2 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I created an Ubuntu 14.04.5 LTS VM which initially had:
```
derek@ubuntu:~/dr/git/build_x86_dbg_tests$ uname -a
Linux ubuntu 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

With that kernel I could not reproduce the 32-bit test failures.
But after an update and dist-upgrade and reboot I now had this kernel, more closely matching the new Travis:

```
derek@ubuntu:~/dr/git/build_x86_dbg_tests$ uname -a
Linux ubuntu 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

And now I can repro the 32-bit failures.  The kernel accepts the exec (i.e., the syscall does not fail) but then exits the process early, so there's some kernel change where it can't handle libdynamorio.so:

```
Breakpoint 2, execute_exec (info=0x80c41e0, 
    toexec=0xffff9138 "/home/derek/dr/git/build_x86_dbg_tests/bin32/../lib32/debug/libdynamorio.so")
    at /home/derek/dr/git/src/core/unix/injector.c:309
309	    execv(toexec, (char **) info->argv);
(gdb) p toexec
$1 = 0xffff9138 "/home/derek/dr/git/build_x86_dbg_tests/bin32/../lib32/debug/libdynamorio.so"
(gdb) next
process 2457 is executing new program: /home/derek/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so
[Inferior 1 (process 2457) exited with code 0377]
```

**Comment by derekbruening** [comment]
Kernel 4.4.0-93 did cause some problems with the sanitizer shadow mappings.  I wouldn't expect it to matter b/c libdynamorio.so should handle any load base, but it's worth looking into b/c it is the same kernel version:

Moving PIE load points around: 
https://github.com/torvalds/linux/commit/eab09532d40090698b05a07c1c87f39fdbc5fab5

Reverted for x64:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=c715b72c1ba406f133217b509044c38d8e714a37

**Comment by derekbruening** [comment]
OK so gdb is just being misleading: this is a user-mode crash, it's not the kernel rejecting the exec.  Putting breakpoints in makes this clear.

The crash is due to an ASSERT_CURIOSITY:

```
(gdb) bt
#0  memquery_library_bounds_by_iterator (name=0xf7f606fe "libdynamorio.so", start=0xffffcac4, end=0xffffcac0, 
    fullpath=0xf7ff4120 <dynamorio_library_path> "/home/derek/dr/git/build_x86_dbg_tests/lib32/debug/", path_size=512)
    at /home/derek/dr/git/src/core/unix/memquery.c:214
#1  0xf7ecb8df in memquery_library_bounds (name=0xf7f606fe "libdynamorio.so", start=0xffffcac4, end=0xffffcac0, 
    fullpath=0xf7ff4120 <dynamorio_library_path> "/home/derek/dr/git/build_x86_dbg_tests/lib32/debug/", path_size=512)
    at /home/derek/dr/git/src/core/unix/memquery_linux.c:316
#2  0xf7eaba25 in get_dynamo_library_bounds () at /home/derek/dr/git/src/core/unix/os.c:8676
#3  0xf7eac128 in get_dynamorio_dll_start () at /home/derek/dr/git/src/core/unix/os.c:8847
#4  0xf7eca0eb in privload_early_inject (sp=0xffffd0e0, old_libdr_base=0x0, old_libdr_size=0)
    at /home/derek/dr/git/src/core/unix/loader.c:1760
(gdb) 
214	        ASSERT_CURIOSITY(image_size == 0 || cur_end - mod_start == image_size);
(gdb) 
[Inferior 1 (process 12042) exited with code 0377]
```

```
derek@ubuntu:~/dr/git/build_x86_dbg_tests$ cat /proc/12065/maps
f7bf5000-f7bf7000 r--p 00000000 00:00 0                                  [vvar]
f7bf7000-f7bf9000 r-xp 00000000 00:00 0                                  [vdso]
f7bf9000-f7f96000 r-xp 00000000 08:01 1077027                            /home/derek/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so
f7f96000-f7fd4000 rw-p 0039c000 08:01 1077027                            /home/derek/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so
f7fd4000-f7ffe000 rw-p 00000000 00:00 0                                  [heap]
fffdd000-ffffe000 rw-p 00000000 00:00 0                                  [stack]
```

```
(gdb) info local
count = 2
found_library = true
libname = "/home/derek/dr/git/build_x86_dbg_tests/lib32/debug/libdynamorio.so", '\000' <repeats 445 times>
name_cmp = 0xf7f606fe "libdynamorio.so"
iter = {vm_start = 0xf7fd4000 <optionbuff+32> "", vm_end = 0xf7ffe000 <error: Cannot access memory at address 0xf7ffe000>, 
  prot = 3, offset = 0, inode = 0, comment = 0xf7ff79e0 <comment_buf_scratch> "[heap]", may_alloc = false, 
  internal = "\004\000\000\000\307k\377\367Y\002\000\000\a\020\000\000\300i\377\367\340y\377\367", '\000' <repeats 71 times>}
target = 0xf7bf9000 "\177ELF\001\001\001"
last_lib_base = 0xf7bf7000 "\177ELF\001\001\001"
last_lib_end = 0xf7f96000 "\205\002B\r\005E\206\003\203\004\003@\001\303A\306A\305\f\004\004"
prev_base = 0xf7f96000 "\205\002B\r\005E\206\003\203\004\003@\001\303A\306A\305\f\004\004"
prev_end = 0xf7fd4000 <optionbuff+32> ""
prev_prot = 3
image_size = 4096
cur_end = 0xf7fd4000 <optionbuff+32> ""
mod_start = 0xf7bf7000 "\177ELF\001\001\001"
__FUNCTION__ = "memquery_library_bounds_by_iterator"
(gdb) p cur_end - mod_start
$9 = 4050944
(gdb) p *start
$10 = (app_pc) 0xf7bf9000 "\177ELF\001\001\001"
```

So module_walk_program_headers computed the wrong size.  mod_start points
at the vdso.
I think it's the #2566 changes to include a prior anon mapping for
hugepage text which is making it try to include the vdso.  And this only
happens on this kernel b/c they moved where vdso is to be right before the
exe.

**Comment by derekbruening** [comment]
The 32-bit failures are *all* fixed, and most of the 64-bit, but these 2 64-bit failures remain:

```
debug-internal-64: 273 tests passed, **** 2 tests failed: ****
	code_api|linux.clone 
	code_api|linux.exit 
```

**Comment by derekbruening** [comment]
Unfortunately I can't reproduce those 2 64-bit failures in my VM...

**Comment by derekbruening** [comment]
Hmm next PR has 2 different failures:

https://travis-ci.org/DynamoRIO/dynamorio/jobs/276032337
```
debug-internal-64: 273 tests passed, **** 2 tests failed: ****
	code_api|sample.prefetch 
	code_api|sample.stl_test 
```

**Comment by derekbruening** [comment]
I'm going to split the weird non-det 64-bit failures into a separate issue and make this one about the 32-bit early injection memquery crash => #2641
