### ISSUE TITLE
HANG running any Go program

### ISSUE THREAD

**Issue by FiloSottile** [DynamoRIO/dynamorio#3171]
* DynamoRIO version: 7.0.0-rc1
* Operating system: 64-bit Linux (within a Debian Docker container)
* Application: any Go program, including "Hello world", compiled with `GOOS=linux CGO_ENABLED=0`

```
package main

func main() {
	println("Hello, World!")
}
```

```
$ drrun -debug -root $DYNAMORIO_HOME -- /usr/local/src/flagscov/hello_world
<Starting application /usr/local/src/flagscov/hello_world (18)>
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/usr/local/share/DynamoRIO-Linux-7.0.0-RC1/lib64/debug/libdynamorio.so' 0x00007f3f0ff72a68
>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Application tried to execute from dr memory 0x000000004a4cede0.
This may be a result of an unsuccessful attack or a potential application vulnerability.>
^\SIGQUIT: quit
PC=0x4086f6 m=0 sigcode=128

goroutine 0 [idle]:
runtime.notesleep(0x4bb4e0)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/lock_futex.go:149 +0x76
runtime.stoplockedm()
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:2165 +0x8a
runtime.schedule()
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:2565 +0x2d9
runtime.park_m(0xc000000300)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x470ba8, 0xc00005c058, 0xc00001170d, 0x3)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:302 +0xeb
runtime.goparkunlock(0xc00005c058, 0x170d, 0x3)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:308 +0x53
runtime.chanrecv(0xc00005c000, 0x0, 0xc000000301, 0x411498)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/chan.go:520 +0x2be
runtime.chanrecv1(0xc00005c000, 0x0)
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/chan.go:402 +0x2b
runtime.gcenable()
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/mgc.go:217 +0x6f
runtime.main()
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/proc.go:164 +0x119
runtime.goexit()
	/Users/valsorda/homebrew/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333 +0x1

rax    0x4bae20
rbx    0x4
rcx    0xffffffffffffffff
rdx    0x989680
rdi    0x0
rsi    0x1
rbp    0x7ffd5c30a598
rsp    0x7ffd5c30a570
r8     0xc000042700
r9     0xc000000f00
r10    0x8
r11    0x282
r12    0x426910
r13    0x11
r14    0x476d78
r15    0x0
rip    0x4086f6
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
<Stopping application /usr/local/src/flagscov/hello_world (18)>
```

The SIGQUIT information might or might not be useful, depending how confused the Go runtime that's printing it is.

**Comment by derekbruening** [comment]
First the app somehow gets a DR address in a retaddr slot right after a
SYS_arch_prctl(ARCH_SET_FS) call which may be worth looking at as it's unusual:
```
interp: start_pc = 0x000000000044e985
check_thread_vm_area: pc = 0x000000000044e985
prepend_entry_to_fraglist: putting fragment @0x000000000044e985 (shared) on vmarea 0x0000000000400000-0x000000000047e000
  0x000000000044e985  49 89 40 48          mov    %rax -> 0x48(%r8)[8byte]
  0x000000000044e989  49 8d 78 60          lea    0x60(%r8) -> %rdi
  0x000000000044e98d  e8 5e 00 00 00       call   $0x000000000044e9f0 %rsp -> %rsp 0xfffffff8(%rsp)[8byte]
interp: direct call at 0x000000000044e98d
        NOT following direct call from 0x000000000044e98d to 0x000000000044e9f0
end_pc = 0x000000000044e992

Entry into F2088(0x000000000044e985).0x000000004f702438 (shared)
        
fcache_enter = 0x000000004f5f0d00, target = 0x000000004f702438
Exit from F15(0x000000000044e9f0).0x000000004f61626b (shared)   
 (block ends with syscall)
Entry into do_syscall to execute a non-ignorable system call
system call 158
fcache_enter = 0x000000004f5f0d00, target = 0x000000004f5f1c40
Exit from system call
post syscall: sysnum=0x000000000000009e, result=0x0000000000000000 (0)
thread 12854 segment change => app lib tls base: 0x000000c420010468, alt tls base: 0x0000000000000000
finished handling system call

Entry into F16(0x000000000044ea15).0x000000004f616278 (shared)

Exit from sourceless ibl: bb ret        
 (target 0x00007fd1128ffcab not in cache)

interp: start_pc = 0x00007fd1128ffcab
check_thread_vm_area: pc = 0x00007fd1128ffcab
new shared vm area: 0x00007fd1128a5000-0x00007fd112c35000 ---- ELF SO libdynamorio.so
```

That ends up leading to a SIGILL:
```
interp: start_pc = 0x00007fd112bdf542
check_thread_vm_area: pc = 0x00007fd112bdf542
prepend_entry_to_fraglist: putting fragment @0x00007fd112bdf542 (shared) on vmarea 0x00007fd1128a5000-0x00007fd112c35000
decode: invalid instr at 0x00007fd112bdf542
  0x00007fd112bdf542  61...??              <INVALID>
  0x00007fd112bdf543  72 65                jb     $0x00007fd112bdf5aa
        reads flag before writing it!
end_pc = 0x00007fd112bdf545

master_signal_handler: thread=12854, sig=4, retaddr=0x00007fd112b1b8c8

Going to receive signal now
blocked signals are now:
        1 = blocked
        <...>
        64 = blocked
```

The app's handler is invoked which blocks all signals:
```
  0x00000000004370b6  e8 15 0a 00 00       call   $0x0000000000437ad0 %rsp -> %rsp 0xfffffff8(%rsp)[8byte]
interp: direct call at 0x00000000004370b6
        NOT following direct call from 0x00000000004370b6 to 0x0000000000437ad0
end_pc = 0x00000000004370bb

interp: start_pc = 0x0000000000437ad0
check_thread_vm_area: pc = 0x0000000000437ad0
prepend_entry_to_fraglist: putting fragment @0x0000000000437ad0 (shared) on vmarea 0x0000000000400000-0x000000000047e000
  0x0000000000437ad0  48 83 ec 38          sub    $0x0000000000000038 %rsp -> %rsp
        wrote all 6 flags now!
  0x0000000000437ad4  48 89 6c 24 30       mov    %rbp -> 0x30(%rsp)[8byte]
  0x0000000000437ad9  48 8d 6c 24 30       lea    0x30(%rsp) -> %rbp
  0x0000000000437ade  8b 44 24 40          mov    0x40(%rsp)[4byte] -> %eax
  0x0000000000437ae2  83 f8 41             cmp    %eax $0x00000041
  0x0000000000437ae5  0f 83 7d 01 00 00    jnb    $0x0000000000437c68
end_pc = 0x0000000000437aeb

interp: start_pc = 0x0000000000437c68
check_thread_vm_area: pc = 0x0000000000437c68
prepend_entry_to_fraglist: putting fragment @0x0000000000437c68 (shared) on vmarea 0x0000000000400000-0x000000000047e000
  0x0000000000437c68  c6 44 24 58 00       mov    $0x00 -> 0x58(%rsp)[1byte]
  0x0000000000437c6d  48 8b 6c 24 30       mov    0x30(%rsp)[8byte] -> %rbp
  0x0000000000437c72  48 83 c4 38          add    $0x0000000000000038 %rsp -> %rsp
        wrote all 6 flags now!
  0x0000000000437c76  c3                   ret    %rsp (%rsp)[8byte] -> %rsp
mbr exit target = 0x000000004f5f1540
end_pc = 0x0000000000437c77

Exit from sourceless ibl: bb ret        
 (target 0xffffffff4f75a166 not in cache)
```

Somehow a retaddr within the handler gets a bogus address.

We then hit an infinite loop as DR tries to raise SIGSEGV:
```
dispatch: target = 0xffffffff4f75a166

interp: start_pc = 0xffffffff4f75a166
check_thread_vm_area: pc = 0xffffffff4f75a166
application tried to execute from unreadable 0xffffffff4f75a166 is_allocated_mem=0 prot=0x0
Thread 12854 call stack:
        0xffffffff4f75a166  
        frame ptr 0x000000004f75a164 => parent 0x3631613537663466, 0x4f75a1e400000a36  
record_pending_signal(11 at pc 0xffffffff4f75a166): signal is currently blocked
        action is not SIG_IGN
        retaddr = 0x000000000044e810
        non-rt signal already in queue, ignoring this one!
transfer_to_dispatch: pc=0x4f75a166, xsp=0x000000004f75a100, initstack=0
Exit from asynch event

dispatch: target = 0xffffffff4f75a166

interp: start_pc = 0xffffffff4f75a166
check_thread_vm_area: pc = 0xffffffff4f75a166
application tried to execute from unreadable 0xffffffff4f75a166 is_allocated_mem=0 prot=0x0
Thread 12854 call stack:
        0xffffffff4f75a166  
        frame ptr 0x000000004f75a164 => parent 0x3631613537663466, 0x4f75a1e400000a36  
record_pending_signal(11 at pc 0xffffffff4f75a166): signal is currently blocked
        action is not SIG_IGN
        retaddr = 0x000000000044e810
        non-rt signal already in queue, ignoring this one!
transfer_to_dispatch: pc=0x4f75a166, xsp=0x000000004f75a100, initstack=0
Exit from asynch event
```

That first DR address is:

(gdb) x/4i 0x7f98f7353000 - 0x00007fd1128a5000 + 0x00007fd1128ffcab - 5
   0x7f98f73adca6 <fragment_lookup+35>:	callq  0x7f98f73ad659 <fragment_lookup_type>
   0x7f98f73adcab <fragment_lookup+40>:	leaveq 
   0x7f98f73adcac <fragment_lookup+41>:	retq   

Looking backward, looks like this thread suddenly uses the DR stack,
explaining all the retaddr corruption:
```
DR stack is 0x000000004f74d000-0x000000004f75b000 (passed in 0x000000004f75b000)

initial dispatch: target = 0x000000000044e964
Call stack:
Thread 12854 call stack:
        frame ptr 0x00007fffe0981628 => parent 0x00007fffe0981678, 0x000000000042b857  
        frame ptr 0x00007fffe0981678 => parent 0x00007fffe0981698, 0x0000000000449f36  
        frame ptr 0x00007fffe0981698 => parent 0x000000c42002c7d0, 0x000000000044af49  
        frame ptr 0x000000c42002c7d0 => parent 0x0000000000000000, 0x000000000044d4a1  
priv_mcontext_t @0x000000004f609980
        xax = 0x0000000000000000
        xbx = 0x0000000000000000
        xcx = 0x000000004f5f1d42
        xdx = 0x0000000000000000
        xsi = 0x000000004f75a8c0
        xdi = 0x0000000000010f00
        xbp = 0x00007fffe0981628
        xsp = 0x000000c42003e000

interp: start_pc = 0x000000000044e96f
check_thread_vm_area: pc = 0x000000000044e96f
prepend_entry_to_fraglist: putting fragment @0x000000000044e96f (shared) on vmarea 0x0000000000400000-0x000000000047e000
  0x000000000044e96f  48 89 f4             mov    %rsi -> %rsp
  0x000000000044e972  49 83 f8 00          cmp    %r8 $0x0000000000000000
        wrote all 6 flags now!
  0x000000000044e976  74 2c                jz     $0x000000000044e9a4
end_pc = 0x000000000044e978

priv_mcontext_t @0x000000004f609980
        xax = 0x0000000000000000
        xbx = 0x0000000000000000
        xcx = 0x000000004f5f1d42
        xdx = 0x0000000000000000
        xsi = 0x000000004f75a8c0
        xdi = 0x0000000000010f00
        xbp = 0x00007fffe0981628
        xsp = 0x000000004f75a8c0
```

rsi came from parent which passes it to SYS_clone:
```
check_thread_vm_area: pc = 0x000000000044e940
prepend_entry_to_fraglist: putting fragment @0x000000000044e940 (shared) on vmarea 0x0000000000400000-0x000000000047e000
  0x000000000044e940  8b 7c 24 08          mov    0x08(%rsp)[4byte] -> %edi
  0x000000000044e944  48 8b 74 24 10       mov    0x10(%rsp)[8byte] -> %rsi
  0x000000000044e949  31 d2                xor    %edx %edx -> %edx
        wrote all 6 flags now!
  0x000000000044e94b  45 31 d2             xor    %r10d %r10d -> %r10d
  0x000000000044e94e  4c 8b 44 24 18       mov    0x18(%rsp)[8byte] -> %r8
  0x000000000044e953  4c 8b 4c 24 20       mov    0x20(%rsp)[8byte] -> %r9
  0x000000000044e958  4c 8b 64 24 28       mov    0x28(%rsp)[8byte] -> %r12
  0x000000000044e95d  b8 38 00 00 00       mov    $0x00000038 -> %eax
  0x000000000044e962  0f 05                syscall  -> %rcx
interp: syscall @ 0x000000000044e962
find_syscall_num: found syscall number write: 56

system call 56
syscall: clone with flags = 0x0000000000010f00
args: 0x0000000000010f00, 0x000000c42003e000, 0x0000000000000000, 0x0000000000000000, 0x000000c420010400
handle_clone: CLONE_SIGHAND set!
create_clone_record: dstack for new thread is 0x000000004f75b000
allocated clone record: 0x000000004f75a8e0
create_clone_record: thread 12852, pc 0x000000000044e964
tls_get_fs_gs_segment_base selector 0 index 0 ldt 0
arch_prctl fs => 0x00000000004fcea8
TLS copy is 0x000000004f5d2270
fcache_enter = 0x000000004f5f0d00, target = 0x000000004f5f1d40
Exit from system call
post syscall: sysnum=0x0000000000000038, result=0x0000000000003236 (12854)
syscall: clone returned 0x0000000000003236
tls_get_fs_gs_segment_base selector 0 index 0 ldt 0
arch_prctl fs => 0x000000004f65a700
finished handling system call
```

rsi passed to syscall is 0xc42003e000, which is the new rsp.
Yet rsi post-syscall holds value very close to clone record.

DR changes rsi to the dstack, and in new_thread_setup() it sets rsp but
never restores the syscall param rsi.  No other program has ever looked at
it.

Fixing it => it works:
```
$ ninja && bin64/drrun -- ~/go/src/hello/hello
<Starting application /home/bruening/go/src/hello/hello (70096)>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00007f0ffdb6f650
>
hello, world
<Stopping application /home/bruening/go/src/hello/hello (70096)>
```

TODO: abort rather than infinite looping for the SIGSEGV-blocked
artificial-signal case.

**Comment by FiloSottile** [comment]
Wonderful, thank you! LMK if you want me to test a PR with more complex applications.

**Comment by derekbruening** [comment]
Fixed in 49ee692223553f642ecd2ad28e5fcee4b51135df
It would be great to have a test but it's non-trivial to add Go into our suite and I decided not to check in a binary.

> Wonderful, thank you! LMK if you want me to test a PR with more complex applications.

Please re-open if this doesn't fix your hello,world Go program; please file a new issue if you hit something else on larger apps.

**Comment by derekbruening** [comment]
FYI, there are weekly "cronbuilds" but they're on Mondays so you could either wait a week or build from sources now.

**Comment by FiloSottile** [comment]
It actually worked on the bigger application as well. I'm impressed by the performance of `instrace_simple`. Thank you for the quick fix!

**Comment by derekbruening** [comment]
> It actually worked on the bigger application as well.

That's good to hear.

> I'm impressed by the performance of instrace_simple

FYI, instrace_x86_binary is faster, and if you are ok with further post-processing, the drcachesim tracer's approach is faster still (but it does not have an instruction-only option today so it would take a little work to adapt it).
