### ISSUE TITLE
make unknown instruction handling more robust

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3212]
Today DR's handling of an instruction that is considered invalid according to DR's decode tables is not ideal: on Linux, DR isolates the instruction to a single bb and then executes the bb, expecting it to fault right away.  On Windows, DR forges an illegal instruction exception.

If the instruction is in fact valid, DR does not necessarily do the right thing for continued execution.  Its handling is especially problematic with variable-length instructions.  DR doesn't know the length of the instruction, so it copies the maximum (17 bytes on x86).  It's possible that the instruction is valid (a new ISA extension not yet added to DR, e.g., or a non-public instruction encoding) and that there are control flow or other instructions that need mangling in those 17 bytes.  DR could lose control or crash.

How do we improve this?  Maybe we should decode the 17 bytes from every offset and ensure there are no control flow instructions to at least not lose control (the wrong thing will still happen in terms of a client not seeing instructions) and perhaps also look for other key things like segment references, rip-rel references, or (for ARM) stolen register use.  It's not clear what to do if we see these things: try to single-step (via debugger methods or via running progressively longer sequences and counting instructions via perfctrs...just talking out loud here).

Or maybe we should acknowledge that there is no good solution and change Linux to also explicitly forge SIGILL up front.  There are tradeoffs here with new ISA support.

Note that for core DR with the fast decoder we deliberately gloss over invalid entries within opcode classes: if we can guess at the length we go with it.  When a client is there this may not be the case as the full decoder might complain: we should double-check the difference and see if we can do better for the full decoder.

Xref #57
Xref #431

**Comment by derekbruening** [comment]
We were recently burned by bad behavior around invalid instruction handling for an actually-valid instruction.  I filed #3939 but I'm merging it into here.  I'm duplicating that data here for convenience:

This was observed before the #2431 fix, where crc32w was considered invalid.

This is the app code:
```
0000000000401006 <test_bb>:
  401006:	31 c9                	xor    %ecx,%ecx
  401008:	45 31 c0             	xor    %r8d,%r8d
  40100b:	66 f2 44 0f 38 f1 c1 	crc32w %cx,%r8d
  401012:	48 83 f8 04          	cmp    $0x4,%rax
  401016:	eb 00                	jmp    401018 <next_bb>

0000000000401018 <next_bb>:
  401018:	48 c7 c3 10 00 00 00 	mov    $0x10,%rbx
000000000040101f <loop>:
  40101f:	48 c7 c7 01 00 00 00 	mov    $0x1,%rdi
```

```
  0x0000000000401008  45 31 c0             xor    %r8d %r8d -> %r8d
  0x000000000040100b  66 f2 44 0f 38 f1 c1...??  <INVALID>
```

DR puts the invalid instr into its own bb.  But it ends up w/ weirdness afterward:
```
bb ilist after mangling:
TAG  0x000000000040100b
 +0    L0                      66 f2 44 0f 38 f1 c1...??  <INVALID>
 +0    L4 @0x00007f69a6542818  e9 27 26 ec 59       jmp    $0x000000000040101c
END 0x000000000040100b

  -------- normal entry: --------
  0x000000004491b1f8  66 f2 44 0f 38 f1 c1...??  <INVALID>
  0x000000004491b1ff  48 83 f8 04          cmp    %rax $0x0000000000000004
  0x000000004491b203  eb 00                jmp    $0x000000004491b205
  0x000000004491b205  48 c7 c3 10 e9 58 fe mov    $0xfffffffffe58e910 -> %rbx
  0x000000004491b20c  00 00                add    %al (%rax)[1byte] -> (%rax)[1byte]
  -------- exit stub 0: -------- <target: 0x000000000040101c> type: fall-through/speculated/IAT
```

I think DR is copying 17 bytes (max instr size) (post-mangling?? or length not showing up on instrlist disasm of invalid instr?), but what happened to the exit cti??  And the OP_add faults, and we don't know how to xl8 it.

DR then crashes while translating:
```
For SIGSEGV at cache pc 0x000000004491b20c, computed target write 0x0000000000000000
        faulting instr: add    %al (%rax)[1byte] -> (%rax)[1byte]
+* Received SIGSEGV at cache pc 0x000000004491b20c in thread 25210
<...>
recreate_app : pc is in F3(0x000000000040100b)
recreate_app : looking for 0x000000004491b20c in frag @ 0x000000004491b1e4 (tag 0x000000000040100b)
translation info 0x00007f69a657be60
        0 +    0 == 0x000000004491b1e4 => 0x000000000040100b identical ours
        1 +   20 == 0x000000004491b1f8 => 0x000000000040100b identical
        2 +   37 == 0x000000004491b209 => 0x000000000040100b identical ours

master_signal_handler: thread=25210, sig=11, xsp=0x00007f69a6558cb8, retaddr=0x00007f6a2675e73d
<...>
For SIGSEGV at cache pc 0x00007f6a266fba6f, computed target read 0x0000000000000000
        faulting instr: movzx  (%rax)[1byte] -> %eax
SYSLOG_CRITICAL: Application dr/test/allasm_x64 (25210).  DynamoRIO Cache Simulator Tracer internal crash at PC 0x00007f6a266fba6f.  Please report this at http://dynamorio.org/issues.  Program aborted.
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dbca6f in read_instruction (pc=0x0, orig_pc=0x0, ret_info=0x7fff77c15688, di=0x7fff77c15600, just_opcode=false, report_invalid=true)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:963
963	        instr_byte = *pc;
(gdb) bt
#0  0x00007ffff7dbca6f in read_instruction (pc=0x0, orig_pc=0x0, ret_info=0x7fff77c15688, di=0x7fff77c15600, just_opcode=false, report_invalid=true)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:963
#1  0x00007ffff7dc17e3 in decode_common (dcontext=0x7fff77bbb2c0, pc=0x0, orig_pc=0x0, instr=0x7fff77c15760)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:2521
#2  0x00007ffff7dc2335 in decode (dcontext=0x7fff77bbb2c0, pc=0x0, instr=0x7fff77c15760) at /home/bruening/dr/git/src/core/arch/x86/decode.c:2690
#3  0x00007ffff7d78495 in recreate_app_state_from_info (tdcontext=0x7fff77bbb2c0, info=0x7fff77c37e60, start_cache=0x422831e4 "\004\177\236geH\241", 
    end_cache=0x4228320e '\253' <repeats 200 times>..., mc=0x7fff77c16bf0, just_pc=false, flags=553648176)
    at /home/bruening/dr/git/src/core/translate.c:657
#4  0x00007ffff7d7aeb1 in recreate_app_state_internal (tdcontext=0x7fff77bbb2c0, mcontext=0x7fff77c16bf0, just_pc=false, owning_f=0x7fff77bd2f58, 
    restore_memory=true) at /home/bruening/dr/git/src/core/translate.c:1270
#5  0x00007ffff7d7b55c in recreate_app_state (tdcontext=0x7fff77bbb2c0, mcontext=0x7fff77c16bf0, restore_memory=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/translate.c:1432
#6  0x00007ffff7d53c3c in translate_mcontext (trec=0x7fff77bb1620, mcontext=0x7fff77c16bf0, restore_memory=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/synch.c:465
#7  0x00007ffff7e57776 in translate_sigcontext (dcontext=0x7fff77bbb2c0, uc=0x7fff77c179c0, avoid_failure=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/unix/signal.c:2603
#8  0x00007ffff7e5d559 in record_pending_signal (dcontext=0x7fff77bbb2c0, sig=11, ucxt=0x7fff77c179c0, frame=0x7fff77c179b8, forged=false, 
    access_address=0x0) at /home/bruening/dr/git/src/core/unix/signal.c:4326
#9  0x00007ffff7e60d9f in master_signal_handler_C (sig=11, siginfo=0x7fff77c17af0, ucxt=0x7fff77c179c0, xsp=0x7fff77c179b8 "=\367\341\367\377\177")
    at /home/bruening/dr/git/src/core/unix/signal.c:5281
(gdb) x/4i $pc
=> 0x7ffff7dbca6f <read_instruction+225>:	movzbl (%rax),%eax
   0x7ffff7dbca72 <read_instruction+228>:	mov    %al,-0x19(%rbp)
```

While it's not easy to handle instructions where DR thinks they're invalid but they aren't, we should at least do better than this: something is wrong in that emitted code, and we should also try to fix this translation crash if we can.

**Comment by derekbruening** [comment]
Looking more closely, the exit cti is there, but the prior instr ends mid-instr, so the exit cti is swallowed up.

The best thing seems to be to make Linux like Windows: just forge a fault immediately.  This makes it clear where the problem is and avoids all the complexities of the fragile bb.  It is not good for the client but that's #1000.

**Comment by derekbruening** [comment]
Looking at the common.decode-bad test which has invalid instrs in it, it looks like we just get lucky at the instr boundaries:

```
  -------- normal entry: --------
decode: invalid lock prefix at 0x00000000423f8978
  0x00000000423f8978  f0 eb 00...??        <INVALID>
  0x00000000423f897b  48 83 c4 00          add    $0x0000000000000000 %rsp -> %rsp
  0x00000000423f897f  41 5f                pop    %rsp (%rsp)[8byte] -> %r15 %rsp
  0x00000000423f8981  41 5e                pop    %rsp (%rsp)[8byte] -> %r14 %rsp
  0x00000000423f8983  41 5d                pop    %rsp (%rsp)[8byte] -> %r13 %rsp
  0x00000000423f8985  41 5c                pop    %rsp (%rsp)[8byte] -> %r12 %rsp
  0x00000000423f8987  5d                   pop    %rsp (%rsp)[8byte] -> %rbp %rsp
  0x00000000423f8988  5b                   pop    %rsp (%rsp)[8byte] -> %rbx %rsp
  0x00000000423f8989  e9 bc 05 ff ff       jmp    $0x00000000423e8f4a
  -------- exit stub 0: -------- <target: 0x0000000000401732> type: fall-through/speculated/IAT

  -------- normal entry: --------
decode: invalid instr at 0x00000000423f8c5c
  0x00000000423f8c5c  df fa...??           <INVALID>
  0x00000000423f8c5e  65 48 89 0c 25 10 00 mov    %rcx -> %gs:0x10[8byte]
                      00 00
  0x00000000423f8c67  59                   pop    %rsp (%rsp)[8byte] -> %rcx %rsp
  0x00000000423f8c68  e9 d3 f8 f9 ff       jmp    $0x0000000042398540 <shared_bb_ibl_ret>
  -------- exit stub 0: -------- <target: 0x0000000042398540> type: ret

decode: invalid instr at 0x00000000423f8cf1
  0x00000000423f8cf1  0f...??              <INVALID>
  0x00000000423f8cf2  04 c3                add    $0xc3 %al -> %al
decode: invalid instr at 0x00000000423f8cf4
  0x00000000423f8cf4  fe 30...??           <INVALID>
  0x00000000423f8cf6  65 48 89 0c 25 10 00 mov    %rcx -> %gs:0x10[8byte]
                      00 00
  0x00000000423f8cff  59                   pop    %rsp (%rsp)[8byte] -> %rcx %rsp
  0x00000000423f8d00  e9 3b f8 f9 ff       jmp    $0x0000000042398540 <shared_bb_ibl_ret>
  -------- exit stub 0: -------- <target: 0x0000000042398540> type: ret
```
