### ISSUE TITLE
crashes on Android device

### ISSUE THREAD

**Issue by 0x1Fu** [DynamoRIO/dynamorio#3679]
Both DynamoRIO-ARM-Android-EABI-7.1.0-1 and the latest version are not working on my Android device,

Logs:
$ dynamorio/bin32/drrun -root /data/local/tmp/dynamorio -c dynamorio/samples/bin32/libsyscall.so -- ./helloworld
Illegal instruction

GDB:
(gdb) r -c dynamorio/samples/bin32/libsyscall.so -- ./helloworld
Starting program: /data/local/tmp/dynamorio/bin32/drrun -c dynamorio/samples/bin32/libsyscall.so -- ./helloworld
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
process 2222 is executing new program: /data/local/tmp/dynamorio/lib32/release/libdynamorio.so

Program received signal SIGILL, Illegal instruction.
0xf75f81bc in ?? ()
(gdb) bt
#0  0xf75f81bc in ?? ()
#1  0xf75e40e2 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Any help would be appreciated.

**Comment by Carrotman42** [comment]
Take a look through this page about debugging q problem with DynamoRIO, in particular try the -debug flag to drrun to actually get some logs: https://github.com/DynamoRIO/drmemory/wiki/Debugging

Further, please describe precisely what helloworld is doing: is it really just main with a printf as in the classic "Hello World"?

Also, if I'm reading the post right, your GDB invocation did not include the -root flag like your direct invocation does. Not sure if that was intentional.

**Comment by Carrotman42** [comment]
Also, please post questions like this to the user group: https://groups.google.com/forum/m/#!forum/dynamorio-users

We prefer to leave this issue tracker for tracking bugs after we are sure they are bugs; often questions like these are not really problems with DR, but it is indeed hard to tell for sure without more information. Starting on the user group is a good default if you are unsure.

**Comment by ZaccurLi** [comment]
the same issue on my binary：
DynamoRIO-ARM-Android-EABI-8.0.0-1
test_dynamorio : only new and delete 10 blocks
```
/data/local/tmp/dynamorio # bin32/drrun -verbose -debug -c samples/bin32/libempty.so -- ../test_dynamorio                                                                
INFO: client 0 path: /data/local/tmp/dynamorio/samples/bin32/libempty.so
INFO: targeting application: "/data/local/tmp/test_dynamorio"
INFO: app cmdline:  "../test_dynamorio"
INFO: configuration directory is "/data/local/tmp/.dynamorio"
INFO: will exec /data/local/tmp/test_dynamorio
INFO: registering client with id=0 path=|/data/local/tmp/dynamorio/samples/bin32/libempty.so| ops=||
<Starting application /data/local/tmp/test_dynamorio (9146)>
<Initial options = -no_dynamic_options -client_lib '/data/local/tmp/dynamorio/samples/bin32/libempty.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
Illegal instruction 
```


without any client, there may be some faults too.
```
dipper:/data/local/tmp/dynamorio # bin32/drrun -root ./ -verbose -debug -stats -- ../test_dynamo                                                                                    
INFO: targeting application: "/data/local/tmp/test_dynamo"
INFO: app cmdline:  "../test_dynamo"
INFO: configuration directory is "/data/local/tmp/.dynamorio"
INFO: will exec /data/local/tmp/test_dynamo
<Starting application /data/local/tmp/test_dynamo (9137)>
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/data/local/tmp/dynamorio/lib32/debug/libdynamorio.so' 0xea2f7ad0
>
<get_memory_info mismatch! (can happen if os combines entries in /proc/pid/maps)
	os says: 0xea2cb000-0xea2d4000 prot=0x00000003
	cache says: 0xea2cd000-0xea2ce000 prot=0x00000003
>
<(1+x) Handling our fault in a TRY at 0xea4b336c>
<CURIOSITY : (0) && "crashed while walking dynamic header" in file /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c line 328
version 8.0.0, build 1
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0xea3642dd 0x78af04b0>
<CURIOSITY : (0) && "crashed while walking dynamic header" in file /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c line 328
version 8.0.0, build 1
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0xea3642dd 0x78af04b0>
<CURIOSITY : (0) && "crashed while walking dynamic header" in file /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c line 328
version 8.0.0, build 1
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0xea3642dd 0x78af04b0>
<CURIOSITY : (0) && "crashed while walking dynamic header" in file /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c line 328
version 8.0.0, build 1
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0xea3642dd 0x78af04b0>
C-Style malloc Done
CC/CPP new/delete Done
C-Style free Done
<Stopping application /data/local/tmp/test_dynamo (9137)>

```

**Comment by ZaccurLi** [comment]
@Carrotman42 https://github.com/DynamoRIO/dynamorio/issues/3679#issuecomment-752025020

**Comment by derekbruening** [comment]
@ZaccurLi -- Is this Android 9?  And thus a duplicate of #3543?

**Comment by ZaccurLi** [comment]
@derekbruening Yes, the device is Android 9. But after I have modified the privload_call_lib_func as #3543, it dosen't work.
```
diff --git a/core/unix/loader.c b/core/unix/loader.c
index a803590f..af834dab 100644
--- a/core/unix/loader.c
+++ b/core/unix/loader.c
@@ -982,7 +982,9 @@ privload_call_lib_func(fp_t func)
      */
     dummy_argv[0] = dummy_str;
     dummy_argv[1] = NULL;
-    func(1, dummy_argv, our_environ);
+    // The Bionic library for Android 9 have changes from Android 6 that fails dynamorio.
+    // In order to running dynamorio on android9-arm64, we change privload_call_lib_func in a trick way.
+    // func(1, dummy_argv, our_environ);
 }
 
(base) zaccur@ubuntu:dynamorio$ gitlog -3
* ba090bba(2020-12-23)(6 days ago) -Derek Bruening i#1921 native sig: Deliver signals to unmanaged threads (#4636)
* d53fa0ec(2020-12-21)(9 days ago) -Derek Bruening i#4549 GA CI: Fix cronbuild version errors and allow manual (#4635)
* db19e2b9(2020-12-19)(10 days ago) -Abhinav Anil Sharma i#4549 GA: Configure failure notifs to dynamorio-devs (#4631)
```

I build the dynamorio following the https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build#cross-compiling-for-arm-android

unfortunately, I still got the error 
```
/data/local/tmp/build_android2 # bin32/drrun -verbose -- ../test_dynamorio_hello                                                                                         
INFO: targeting application: "/data/local/tmp/test_dynamorio_hello"
INFO: app cmdline:  "../test_dynamorio_hello"
INFO: configuration directory is "/data/local/tmp/.dynamorio"
INFO: will exec /data/local/tmp/test_dynamorio_hello
<Application /data/local/tmp/test_dynamorio_hello (18342).  DynamoRIO internal crash at PC 0xf6a91768.  Please report this at http://dynamorio.org/issues/.  Program aborted.
Received SIGSEGV at pc 0xf6a91768 in thread 18342
Base: 0xf69f0000
Registers:  r0 =0x00000000 r1 =0x00000000 r2 =0x0000eba3 r3 =0xeba30300
	r4 =0x00000000 r5 =0x4e1558c8 r6 =0x00000000 r7 =0x00000000
	r8 =0x4e150c68 r9 =0x4e150c70 r10=0x00000000 r11=0x00000001
	r12=0x00000000 r13=0x4e150c60 r14=0xf6a9165d r15=0xf6a91768
	eflags=0x00071830
version 8.0.18619, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >

```

**Comment by derekbruening** [comment]
Sounds like you're saying it does work after all.  Please use #3543 for further private loader issues, and email the users list or open a separate issue with details if there is a problem, as this is a closed issue with a rather vague title and so not useful for appending.
