### ISSUE TITLE
Invalid instr bb's exit cti is incorrectly inserted and patched, resulting in bad behavior

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3939]
This was observed before the #2431 fix, where crc32w was considered invalid.

This is the app code:
```
0000000000401006 <test_bb>:
  401006:	31 c9                	xor    %ecx,%ecx
  401008:	45 31 c0             	xor    %r8d,%r8d
  40100b:	66 f2 44 0f 38 f1 c1 	crc32w %cx,%r8d
  401012:	48 83 f8 04          	cmp    $0x4,%rax
  401016:	eb 00                	jmp    401018 <next_bb>

0000000000401018 <next_bb>:
  401018:	48 c7 c3 10 00 00 00 	mov    $0x10,%rbx
000000000040101f <loop>:
  40101f:	48 c7 c7 01 00 00 00 	mov    $0x1,%rdi
```

```
  0x0000000000401008  45 31 c0             xor    %r8d %r8d -> %r8d
  0x000000000040100b  66 f2 44 0f 38 f1 c1...??  <INVALID>
```

DR puts the invalid instr into its own bb.  But it ends up w/ weirdness afterward:
```
bb ilist after mangling:
TAG  0x000000000040100b
 +0    L0                      66 f2 44 0f 38 f1 c1...??  <INVALID>
 +0    L4 @0x00007f69a6542818  e9 27 26 ec 59       jmp    $0x000000000040101c
END 0x000000000040100b

  -------- normal entry: --------
  0x000000004491b1f8  66 f2 44 0f 38 f1 c1...??  <INVALID>
  0x000000004491b1ff  48 83 f8 04          cmp    %rax $0x0000000000000004
  0x000000004491b203  eb 00                jmp    $0x000000004491b205
  0x000000004491b205  48 c7 c3 10 e9 58 fe mov    $0xfffffffffe58e910 -> %rbx
  0x000000004491b20c  00 00                add    %al (%rax)[1byte] -> (%rax)[1byte]
  -------- exit stub 0: -------- <target: 0x000000000040101c> type: fall-through/speculated/IAT
```

I think DR is copying 17 bytes (max instr size) (post-mangling?? or length not showing up on instrlist disasm of invalid instr?), but what happened to the exit cti??  And the OP_add faults, and we don't know how to xl8 it.

DR then crashes while translating:
```
For SIGSEGV at cache pc 0x000000004491b20c, computed target write 0x0000000000000000
        faulting instr: add    %al (%rax)[1byte] -> (%rax)[1byte]
+* Received SIGSEGV at cache pc 0x000000004491b20c in thread 25210
<...>
recreate_app : pc is in F3(0x000000000040100b)
recreate_app : looking for 0x000000004491b20c in frag @ 0x000000004491b1e4 (tag 0x000000000040100b)
translation info 0x00007f69a657be60
        0 +    0 == 0x000000004491b1e4 => 0x000000000040100b identical ours
        1 +   20 == 0x000000004491b1f8 => 0x000000000040100b identical
        2 +   37 == 0x000000004491b209 => 0x000000000040100b identical ours

master_signal_handler: thread=25210, sig=11, xsp=0x00007f69a6558cb8, retaddr=0x00007f6a2675e73d
<...>
For SIGSEGV at cache pc 0x00007f6a266fba6f, computed target read 0x0000000000000000
        faulting instr: movzx  (%rax)[1byte] -> %eax
SYSLOG_CRITICAL: Application dr/test/allasm_x64 (25210).  DynamoRIO Cache Simulator Tracer internal crash at PC 0x00007f6a266fba6f.  Please report this at http://dynamorio.org/issues.  Program aborted.
```

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dbca6f in read_instruction (pc=0x0, orig_pc=0x0, ret_info=0x7fff77c15688, di=0x7fff77c15600, just_opcode=false, report_invalid=true)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:963
963	        instr_byte = *pc;
(gdb) bt
#0  0x00007ffff7dbca6f in read_instruction (pc=0x0, orig_pc=0x0, ret_info=0x7fff77c15688, di=0x7fff77c15600, just_opcode=false, report_invalid=true)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:963
#1  0x00007ffff7dc17e3 in decode_common (dcontext=0x7fff77bbb2c0, pc=0x0, orig_pc=0x0, instr=0x7fff77c15760)
    at /home/bruening/dr/git/src/core/arch/x86/decode.c:2521
#2  0x00007ffff7dc2335 in decode (dcontext=0x7fff77bbb2c0, pc=0x0, instr=0x7fff77c15760) at /home/bruening/dr/git/src/core/arch/x86/decode.c:2690
#3  0x00007ffff7d78495 in recreate_app_state_from_info (tdcontext=0x7fff77bbb2c0, info=0x7fff77c37e60, start_cache=0x422831e4 "\004\177\236geH\241", 
    end_cache=0x4228320e '\253' <repeats 200 times>..., mc=0x7fff77c16bf0, just_pc=false, flags=553648176)
    at /home/bruening/dr/git/src/core/translate.c:657
#4  0x00007ffff7d7aeb1 in recreate_app_state_internal (tdcontext=0x7fff77bbb2c0, mcontext=0x7fff77c16bf0, just_pc=false, owning_f=0x7fff77bd2f58, 
    restore_memory=true) at /home/bruening/dr/git/src/core/translate.c:1270
#5  0x00007ffff7d7b55c in recreate_app_state (tdcontext=0x7fff77bbb2c0, mcontext=0x7fff77c16bf0, restore_memory=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/translate.c:1432
#6  0x00007ffff7d53c3c in translate_mcontext (trec=0x7fff77bb1620, mcontext=0x7fff77c16bf0, restore_memory=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/synch.c:465
#7  0x00007ffff7e57776 in translate_sigcontext (dcontext=0x7fff77bbb2c0, uc=0x7fff77c179c0, avoid_failure=true, f=0x7fff77bd2f58)
    at /home/bruening/dr/git/src/core/unix/signal.c:2603
#8  0x00007ffff7e5d559 in record_pending_signal (dcontext=0x7fff77bbb2c0, sig=11, ucxt=0x7fff77c179c0, frame=0x7fff77c179b8, forged=false, 
    access_address=0x0) at /home/bruening/dr/git/src/core/unix/signal.c:4326
#9  0x00007ffff7e60d9f in master_signal_handler_C (sig=11, siginfo=0x7fff77c17af0, ucxt=0x7fff77c179c0, xsp=0x7fff77c179b8 "=\367\341\367\377\177")
    at /home/bruening/dr/git/src/core/unix/signal.c:5281
(gdb) x/4i $pc
=> 0x7ffff7dbca6f <read_instruction+225>:	movzbl (%rax),%eax
   0x7ffff7dbca72 <read_instruction+228>:	mov    %al,-0x19(%rbp)
```

While it's not easy to handle instructions where DR thinks they're invalid but they aren't, we should at least do better than this: something is wrong in that emitted code, and we should also try to fix this translation crash if we can.

**Comment by derekbruening** [comment]
This is broadly speaking a duplicate of issue #3212.  I'm going to merge it into that one.
