### ISSUE TITLE
"Failed to encode instruction" on branch to NULL on AArch64

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4275]
On a proprietary app in debug build I am seeing these errors on some runs:

```
<Internal Error: Failed to encode instruction: 'b      $0x0000000000000000 <shared_bb_ibl_template_ret>'
>
<Internal Error: Failed to encode instruction: 'b      $0x0000000000000000 <shared_bb_ibl_template_ret>'
>
<Internal Error: Failed to encode instruction: 'b      $0x0000000000000000 <shared_bb_ibl_template_ret>'
>
```

I have not had time to investigate further.
The app continues past them, so they are not immediately fatal.

IIRC, DR uses placeholder branch targets during emitting, with the real targets filled in later: but if this were something like that it would be deterministic and would show up on small apps.  So I'm not sure what this is.

**Comment by AssadHashmi** [comment]
I think there are 5 call sites where `INSTR_CREATE_b` is emitted.
Either the branch targets aren't being filled in at all or they are and the encoder fails.
This is an encoder bug we've not seen before, which implies the former, (and it's a pretty straightforward instruction to encode).

I appreciate this is related to a proprietary app. Do you have a non-proprietary test case which replicates the failure?

**Comment by derekbruening** [comment]
On closer inspection: this only happens with -checklevel 0 and in fact I now believe it is a duplicate of #4275.  This is what happens if that assert is ignored (by the -checklevel 0).

So there is something wrong with mangle_syscall_code().  I think augmenting the test suite to ensure that's hit will likely reproduce this.

```
(gdb) bt
#0  dynamorio_syscall () at src/core/drlibc/drlibc_aarch64.asm:66
#1  0x0000fffc20ad13e0 in read_syscall (fd=0, buf=0xfffb9500ace7, nbytes=1) at src/core/drlibc/drlibc_unix.c:297
#2  0x0000fffc20ad156c in os_read (f=0, buf=0xfffb9500ace7, count=1) at src/core/drlibc/drlibc_unix.c:374
#3  0x0000fffc208549f8 in d_r_notify (priority=SYSLOG_ERROR, internal=true, synch=true, substitution_num=0, prefix=0xfffc20b417c0 "SYSLOG_ERROR", 
    fmt=0xfffc20b41788 "Internal Error: Failed to encode instruction: '%s'\n") at src/core/utils.c:1947
#4  0x0000fffc209b1350 in instr_encode_arch (dcontext=0xfffb956e3780, instr=0xfffb9500b778, copy_pc=0x459305cc "\003", final_pc=0x459305cc "\003", 
    check_reachable=true, has_instr_opnds=0x0, assert_reachable=true) at src/core/arch/aarch64/encode.c:178
#5  0x0000fffc209b101c in instr_encode_to_copy (dcontext=0xfffb956e3780, instr=0xfffb9500b778, copy_pc=0x459305cc "\003", final_pc=0x459305cc "\003")
    at src/core/arch/encode_shared.c:132
#6  0x0000fffc20a721a0 in mangle_syscall_code (dcontext=0xfffb956e3780, f=0xfffb9508aa50, pc=0x459305d0 "\001", skip=false)
    at src/core/arch/mangle_shared.c:769
#7  0x0000fffc20aa7fb0 in unlink_fragment_for_signal (dcontext=0xfffb956e3780, f=0xfffb9508aa50, pc=0x459305bc "\310\a\200R")
    at src/core/unix/signal.c:3755
#8  0x0000fffc20aa9f44 in record_pending_signal (dcontext=0xfffb956e3780, sig=27, ucxt=0xfffb9500ee20, frame=0xfffb9500eda0, forged=false, 
    access_address=0x0) at src/core/unix/signal.c:4265
#9  0x0000fffc20aad838 in master_signal_handler_C (sig=27, siginfo=0xfffb9500eda0, ucxt=0xfffb9500ee20, xsp=0xfffb9500eda0 "\033")
    at src/core/unix/signal.c:5317
(gdb) frame 6
(gdb) info local
nxt_pc = 0xfffb9500b810 "`\270"
stop_pc = 0x459305d8 "\200\a"
target = 0x0
prev_pc = 0x459305d0 "\001"
cti_pc = 0x0
skip_pc = 0x459305cc "\003"
instr = {flags = 458752, encoding_hints = 0, length = 4, {bytes = 0x459305cc "\003", label_cb = 0x459305cc}, translation = 0x0, opcode = 16, 
  num_dsts = 0 '\000', num_srcs = 1 '\001', {{src0 = {kind = 3 '\003', size = 182 '\266', aux = {far_pc_seg_selector = 38144, segment = 0, disp = 38144, 
          shift = 38144, flags = 38144}, value = {immed_int = 0, immed_int_multi_part = {low = 0, high = 0}, immed_float = 0, pc = 0x0, instr = 0x0, 
          reg = 0, base_disp = {disp = 0, base_reg = 0, index_reg = 0, pre_index = 0 '\000', extend_type = 0 '\000', scaled = 0 '\000'}, addr = 0x0}}, 
      srcs = 0x0, dsts = 0x0}, label_data = {data = {71219328515, 0, 0, 0}}}, prefixes = 0, eflags = 0, note = 0x0, prev = 0x0, next = 0x0}
cti = {flags = 0, encoding_hints = 0, length = 0, {bytes = 0x0, label_cb = 0x0}, translation = 0x0, opcode = 0, num_dsts = 0 '\000', num_srcs = 0 '\000', {{
      src0 = {kind = 0 '\000', size = 0 '\000', aux = {far_pc_seg_selector = 0, segment = 0, disp = 0, shift = 0, flags = 0}, value = {immed_int = 0, 
          immed_int_multi_part = {low = 0, high = 0}, immed_float = 0, pc = 0x0, instr = 0x0, reg = 0, base_disp = {disp = 0, base_reg = 0, index_reg = 0, 
            pre_index = 0 '\000', extend_type = 0 '\000', scaled = 0 '\000'}, addr = 0x0}}, srcs = 0x0, dsts = 0x0}, label_data = {data = {0, 0, 0, 0}}}, 
  prefixes = 0, eflags = 0, note = 0x0, prev = 0x0, next = 0x0}
(gdb) x/20i f->start_pc
   0x459305b8:  ldr     x0, [x28, #8]
   0x459305bc:  mov     w8, #0x3e                       // #62
   0x459305c0:  sxtw    x0, w0
   0x459305c4:  sxtw    x2, w2
   0x459305c8:  b       0x459305d0
   0x459305cc:  b       0x459305d8
   0x459305d0:  svc     #0x0
   0x459305d4:  b       0x459305f4
   0x459305d8:  stp     x0, x1, [x28]
   0x459305dc:  mov     x0, #0xaaa0                     // #43680
   0x459305e0:  movk    x0, #0x9508, lsl #16
   0x459305e4:  movk    x0, #0xfffb, lsl #32
   0x459305e8:  ldr     x1, [x28, #64]
   0x459305ec:  br      x1
   0x459305f0:  nop
```

I'm closing and will duplicate those details in #4271.
