### ISSUE TITLE
AT&T disassembly of an instruction with a single AVX 512 mask source asserts

### ISSUE THREAD

**Issue by khuey** [DynamoRIO/dynamorio#4567]
```
./clients/bin64/drdisas -syntax intel 62 f2 fe 48 28 c9
 62 f2 fe 48 28 c9    vpmovm2w zmm1 {k1}
./clients/bin64/drdisas -syntax att 62 f2 fe 48 28 c9
Aborted (core dumped)
...
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7bda859 in __GI_abort () at abort.c:79
#2  0x00005555555b0b9a in external_error (file=0x5555555cfdb8 "/home/khuey/dev/dynamorio/core/ir/x86/disassemble.c", line=238, msg=0x5555555cfe4e "missing decode type")
    at /home/khuey/dev/dynamorio/core/ir/decodelib.c:132
#3  0x00005555555ade95 in opnd_disassemble_noimplicit (buf=0x7fffffffdc40 " 62 f2 fe 48 28 c9    vpmovm2w %zmm1 {", bufsz=228, sofar=0x7fffffffdc38, dcontext=0xffffffffffffffff,
    instr=0x7fffffffdb50, optype=0 '\000', opnd=..., prev=false, multiple_encodings=false, dst=false, idx=0x7fffffffda14) at /home/khuey/dev/dynamorio/core/ir/x86/disassemble.c:238
#4  0x00005555555ac705 in instr_disassemble_opnds_noimplicit (buf=0x7fffffffdc40 " 62 f2 fe 48 28 c9    vpmovm2w %zmm1 {", bufsz=228, sofar=0x7fffffffdc38, dcontext=0xffffffffffffffff,
    instr=0x7fffffffdb50) at /home/khuey/dev/dynamorio/core/ir/disassemble_shared.c:976
#5  0x00005555555ad0e3 in internal_instr_disassemble (buf=0x7fffffffdc40 " 62 f2 fe 48 28 c9    vpmovm2w %zmm1 {", bufsz=228, sofar=0x7fffffffdc38, dcontext=0xffffffffffffffff,
    instr=0x7fffffffdb50) at /home/khuey/dev/dynamorio/core/ir/disassemble_shared.c:1139
#6  0x00005555555abac3 in internal_disassemble (buf=0x7fffffffdc40 " 62 f2 fe 48 28 c9    vpmovm2w %zmm1 {", bufsz=228, sofar=0x7fffffffdc38, dcontext=0xffffffffffffffff,
    pc=0x5555556450f0 "b\362\376H", <incomplete sequence \311>, orig_pc=0x5555556450f0 "b\362\376H", <incomplete sequence \311>, with_pc=false, with_bytes=true,
    extra_bytes_prefix=0x5555555cf584 "") at /home/khuey/dev/dynamorio/core/ir/disassemble_shared.c:760
#7  0x00005555555abc2a in internal_disassemble_to_file (dcontext=0xffffffffffffffff, pc=0x5555556450f0 "b\362\376H", <incomplete sequence \311>,
    orig_pc=0x5555556450f0 "b\362\376H", <incomplete sequence \311>, outfile=1, with_pc=false, with_bytes=true, extra_bytes_prefix=0x5555555cf584 "")
    at /home/khuey/dev/dynamorio/core/ir/disassemble_shared.c:789
#8  0x00005555555abd9f in disassemble_with_info (dcontext=0xffffffffffffffff, pc=0x5555556450f0 "b\362\376H", <incomplete sequence \311>, outfile=1, show_pc=false, show_bytes=true)
    at /home/khuey/dev/dynamorio/core/ir/disassemble_shared.c:843
#9  0x0000555555591e4f in main (argc=9, argv=0x7fffffffe288) at /home/khuey/dev/dynamorio/clients/drdisas/drdisas.cpp:202
```

**Comment by derekbruening** [comment]
Note that we would not normally call an assertion failure a "crash" but you're showing no assert message: isn't it supposed to print a usage error?  Wondering why the message doesn't show up?

**Comment by khuey** [comment]
It's due to output buffering on stdout. There's no \n in the printf so it doesn't get written immediately, and then the program aborts.

**Comment by derekbruening** [comment]
> It's due to output buffering on stdout. There's no \n in the printf so it doesn't get written immediately, and then the program aborts.

I see, would be good to fix that.  Maybe it should be stderr as well.

**Comment by khuey** [comment]
Alright I added that to the PR.
