### ISSUE TITLE
ASSERT 32-bit apps on Ubuntu 20: signal.c:5474 syscall_signal || safe_is_in_fcache()

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#5080]
This shows up in many, many 32-bit Dr. Memory tests where I've been attempting to upgrade GA CI there to Ubuntu 20.04 in https://github.com/DynamoRIO/drmemory/pull/2418

```
<Application /home/runner/work/drmemory/drmemory/build_drmemory-dbg-32/tests/fuzz_corpus (30809).  Internal Error: DynamoRIO debug check failure: /home/runner/work/drmemory/drmemory/dynamorio/core/unix/signal.c:5474 syscall_signal || safe_is_in_fcache(dcontext, pc, (byte *)sc->SC_XSP)
2021-09-06T17:30:03.3305727Z 74: (Error occurred @1807 frags in tid 30809)
```

There are 32-bit signal tests failing for plain DR on Ubuntu 20.04 as well in PR #5072 -- but I haven't seen this assert be reported there.  @abhinav92003 could you confirm you haven't see this assert?  It seems weird that it would only show up in Dr. Memory tests.  You would expect similar underlying DR issues and not two different sets of signal problems.

**Comment by abhinav92003** [comment]
> @abhinav92003 could you confirm you haven't see this assert?

No, I haven't seen the above assertion failure. There have been other issues with signals in general -- segmentation fault crash after the app signal handler completes, affecting 20+ tests -- but the above is new, which is indeed weird. After we've fixed it, maybe we should consider adding a similar test in some form to the DR test suite too.

**Comment by derekbruening** [comment]
On closer inspection: this assert is only happening in the drfuzz, drsyscall, drstrace, and drltrace tests.  It seems to only happen when arguments are passed to the clients and looks like a very early crash during init, before any code is run: signal.c concludes it's fcache code but the address seems bogus.

```
$ dynamorio/bin32/drrun -c bin/debug/libdrltracelib.so -config `/home/bruening/drmemory/git/build_x86_dbg_tests/bin//drltrace.config` -- tests/drsyscall_app 
```

```
(gdb) bt
#0  0xe704aac8 in ?? ()
#1  0x7381a5f3 in droption_parser_t::parse_argv (scope=1, argc=2, argv=0x4986bf58, error_msg=0x0, last_index=0x0) at dynamorio/ext/include/droption.h:199
#2  0x73818bf1 in dr_client_main (id=0, argc=2, argv=0x4986bf58) at /home/bruening/drmemory/git/src/drltrace/drltrace.cpp:448
#3  0xf7d9e6d0 in instrument_init () at /home/bruening/drmemory/git/src/dynamorio/core/lib/instrument.c:770
#4  0xf7c3d414 in dynamorio_app_init () at /home/bruening/drmemory/git/src/dynamorio/core/dynamo.c:696
#5  0xf7e8b661 in privload_early_inject (sp=0xffffd150, old_libdr_base=0x0, old_libdr_size=0) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:2030
#6  0xf7e43382 in reloaded_xfer () at /home/bruening/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1187
(gdb) x/4i $pc
=> 0xe704aac8:	Cannot access memory at address 0xe704aac8
```

So it seems like a droption crash maybe coming from this g++ version.  I can reproduce in my Ubuntu20 VM and also on my local laptop.  Those versions are:
```
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
gcc version 10.2.1 20210110 (Debian 10.2.1-6+build2) 
```
Hmm, you'd think we'd have used those before -- but maybe not w/ Dr. Memory, and maybe this droption crash happens to not show up on droptions uses inside the DR repo?

**Comment by derekbruening** [comment]
```
(gdb) bt
#0  0xe704a26c in ?? ()
#1  0x7381a6c5 in droption_parser_t::parse_argv (scope=1, argc=2, argv=0x458eff58, error_msg=0x0, last_index=0x0) at dynamorio/ext/include/droption.h:199
#2  0x73818cd4 in dr_client_main (id=0, argc=2, argv=0x458eff58) at /home/bruening/drmemory/git/src/drltrace/drltrace.cpp:448
#3  0xf7d9f8a7 in instrument_init () at /home/bruening/drmemory/git/src/dynamorio/core/lib/instrument.c:763
#4  0xf7c3f42f in dynamorio_app_init_part_two_finalize () at /home/bruening/drmemory/git/src/dynamorio/core/dynamo.c:711
#5  0xf7e8be09 in privload_early_inject (sp=0xffffcee0, old_libdr_base=0x0, old_libdr_size=0) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:2045
#6  0xf7e43b23 in reloaded_xfer () at /home/bruening/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1183
(gdb) up 1
#1  0x7381a6c5 in droption_parser_t::parse_argv (scope=1, argc=2, argv=0x458eff58, error_msg=0x0, last_index=0x0) at dynamorio/ext/include/droption.h:199
199	                if (op->name_match(argv[i])) {
(gdb) p op
$1 = (droption_parser_t *) 0x7388d3a0 <op_logdir[abi:cxx11]>
(gdb) p *op
$2 = {
  _vptr.droption_parser_t = 0x73870da4 <vtable for droption_t<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >+8>,
  scope_ = 3,
  name_ = "logdir",
  is_specified_ = false,
  desc_short_ = "Log directory to print library call data",
  desc_long_ = "Specify log directory where library call data will be written, in a separate file per process.  The default value is \".\" (current dir).  If set to \"-\", data for all processes are printed to stderr (wa"...,
  flags_ = 0
}
(gdb) p i
$3 = 1
(gdb) p argv[i]
$4 = 0x45956250 "-config"
(gdb) p &op->name_match
Cannot take address of method name_match.
(gdb) p &op->option_takes_arg
Cannot take address of method option_takes_arg.
(gdb) info vtbl op
vtable for 'droption_parser_t' @ 0x73870da4 (subobject @ 0x7388d3a0):
[0]: 0xe704a21c
[1]: 0xe704a244
[2]: 0xe704a26c
[3]: 0xe7045f1c
[4]: 0xe7046238
[5]: 0xe704a5f4
[6]: 0xe70464a0
(gdb) x/2i 0xe704a21c
   0xe704a21c:	Cannot access memory at address 0xe704a21c
```

It's like the vtable wasn't relocated?

There should be just one reloc:
```
$ readelf -r /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so  | grep da4
73870da4  00033101 R_386_32          7382510e   _ZNK10droption_tI[...]
```
It is applied, but then a 2nd reloc clobbers it w/ the bad value!
```
Breakpoint 2, privload_load_process (privmod=0x4b32c664) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:818
818	    privload_os_finalize(privmod);
(gdb) x/8wx 0x73870da4
0x73870da4:	0x00000000	0x00000000	0x00000000	0x00000000
0x73870db4:	0x00000000	0x00000000	0x00000000	0x00000000
(gdb) watch *(int*)0x73870da4
Hardware watchpoint 3: *(int*)0x73870da4
(gdb) c
Continuing.

Breakpoint 2, privload_load_process (privmod=0x4b32c0f0) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:818
818	    privload_os_finalize(privmod);
(gdb) delete 2
(gdb) delete 1
(gdb) c
Continuing.

Hardware watchpoint 3: *(int*)0x73870da4

Old value = 0
New value = 1937920270
0xf7e939f8 in module_relocate_symbol (rel=0x73812278, pd=0x4b329988, is_rela=false) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1537
1537	    case ELF_R_DIRECT: *r_addr = (reg_t)res + (is_rela ? addend : *r_addr); break;
(gdb) bt
#0  0xf7e939f8 in module_relocate_symbol (rel=0x73812278, pd=0x4b329988, is_rela=false) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1537
#1  0xf7e93a9c in module_relocate_rel (modbase=0x73800000 "\177ELF\001\001\001\003", pd=0x4b329988, start=0x73810858, end=0x738124d0) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1573
#2  0xf7e8a1b7 in privload_relocate_os_privmod_data (opd=0x4b329988, mod_base=0x73800000 "\177ELF\001\001\001\003") at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:1122
#3  0xf7e8a3b5 in privload_relocate_mod (mod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:1159
#4  0xf7e88c3e in privload_process_imports (mod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:582
#5  0xf7d97fe3 in privload_load_process (privmod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:811
#6  0xf7d96205 in privload_process_early_mods () at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:139
#7  0xf7d963e5 in loader_init_epilogue (dcontext=0x4b328040) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:203
#8  0xf7c3f3dd in dynamorio_app_init_part_two_finalize () at /home/bruening/drmemory/git/src/dynamorio/core/dynamo.c:670
#9  0xf7e8be09 in privload_early_inject (sp=0xffffcee0, old_libdr_base=0x0, old_libdr_size=0) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:2045
#10 0xf7e43b23 in reloaded_xfer () at /home/bruening/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1183
(gdb) x/8wx 0x73870da4
0x73870da4:	0x7382510e	0x00000000	0x00000000	0x00000000
0x73870db4:	0x00000000	0x00000000	0x00000000	0x00000000
(gdb) x/4i 0x7382510e
   0x7382510e:	push   %ebp
   0x7382510f:	mov    %esp,%ebp
   0x73825111:	call   0x7381bb61
   0x73825116:	add    $0x4beea,%eax
(gdb) c
Continuing.

Hardware watchpoint 3: *(int*)0x73870da4

Old value = 1937920270
New value = -419126756
0xf7e939f8 in module_relocate_symbol (rel=0x73812278, pd=0x4b329988, is_rela=false) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1537
1537	    case ELF_R_DIRECT: *r_addr = (reg_t)res + (is_rela ? addend : *r_addr); break;
(gdb) x/8wx 0x73870da4
0x73870da4:	0xe704a21c	0x73825122	0x73825136	0x73822f8e
0x73870db4:	0x7382311c	0x738252fa	0x73823250	0x00000000
(gdb) bt
#0  0xf7e939f8 in module_relocate_symbol (rel=0x73812278, pd=0x4b329988, is_rela=false) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1537
#1  0xf7e93a9c in module_relocate_rel (modbase=0x73800000 "\177ELF\001\001\001\003", pd=0x4b329988, start=0x73810858, end=0x73813928) at /home/bruening/drmemory/git/src/dynamorio/core/unix/module_elf.c:1573
#2  0xf7e8a253 in privload_relocate_os_privmod_data (opd=0x4b329988, mod_base=0x73800000 "\177ELF\001\001\001\003") at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:1130
#3  0xf7e8a3b5 in privload_relocate_mod (mod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:1159
#4  0xf7e88c3e in privload_process_imports (mod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:582
#5  0xf7d97fe3 in privload_load_process (privmod=0x4b2e1cf8) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:811
#6  0xf7d96205 in privload_process_early_mods () at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:139
#7  0xf7d963e5 in loader_init_epilogue (dcontext=0x4b328040) at /home/bruening/drmemory/git/src/dynamorio/core/loader_shared.c:203
#8  0xf7c3f3dd in dynamorio_app_init_part_two_finalize () at /home/bruening/drmemory/git/src/dynamorio/core/dynamo.c:670
#9  0xf7e8be09 in privload_early_inject (sp=0xffffcee0, old_libdr_base=0x0, old_libdr_size=0) at /home/bruening/drmemory/git/src/dynamorio/core/unix/loader.c:2045
#10 0xf7e43b23 in reloaded_xfer () at /home/bruening/drmemory/git/src/dynamorio/core/arch/x86/x86.asm:1183
```

x64: just the one reloc is applied.

DR starts over in the middle and on 2nd iteration makes the transition 
73871a4c to 7387100c:
```
$ readelf -r /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so  | less
73870fe8  00012b06 R_386_GLOB_DAT    00000000   __gmon_start__
73870fec  00012e06 R_386_GLOB_DAT    00000000   _ITM_registerTMCl[...]
73870ff0  00029906 R_386_GLOB_DAT    7388d740   op_config_file_default
73871a4c  00010801 R_386_32          00000000   __gxx_personality_v0@CXXABI_1.3
7387100c  00000107 R_386_JUMP_SLOT   00000000   instr_free
73871010  00000207 R_386_JUMP_SLOT   00000000   _ZNKSt7__cxx1112b[...]@GLIBCXX_3.4.21
73871014  00000307 R_386_JUMP_SLOT   00000000   _ZNSt7__cxx1112ba[...]@GLIBCXX_3.4.21
73871018  0001b107 R_386_JUMP_SLOT   7381bb2a   _ZN9__gnu_cxx13ne[...]


relocating libdrltracelib.so
XXX reloc @ 0x73870bb4 type=8
XXX reloc @ 0x73870bb8 type=8
XXX reloc @ 0x73870bbc type=8
XXX reloc @ 0x73870bc4 type=8
XXX reloc @ 0x73870be0 type=8
XXX reloc @ 0x73870be4 type=8
--
elf_sym_matches: considering type=2 _ZNK10droption_tIiE17default_as_stringB5cxx11Ev
symbol lookup for _ZNK10droption_tIiE17default_as_stringB5cxx11Ev 0x73823316
XXX reloc @ 0x73870da0 type=1
sym lookup for _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE from libdrltracelib.so
elf_sym_matches: considering type=1 _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE
symbol lookup for _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE 0x73870e20
XXX reloc @ 0x73870da4 type=1
sym lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv from libdrltracelib.so
elf_sym_matches: considering type=2 _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv
symbol lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv 0x7382510e
XXX reloc @ 0x73870da8 type=1
sym lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE18option_takes_2argsEv from libdrltracelib.so
elf_sym_matches: considering type=2 _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE18option_takes_2argsEv
--
elf_sym_matches: considering type=2 _ZNK10droption_tIiE17default_as_stringB5cxx11Ev
symbol lookup for _ZNK10droption_tIiE17default_as_stringB5cxx11Ev 0x73823316
XXX reloc @ 0x73870da0 type=1
sym lookup for _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE from libdrltracelib.so
elf_sym_matches: considering type=1 _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE
symbol lookup for _ZTI10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE 0x73870e20
XXX reloc @ 0x73870da4 type=1
sym lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv from libdrltracelib.so
elf_sym_matches: considering type=2 _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv
symbol lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE16option_takes_argEv 0x7382510e
XXX reloc @ 0x73870da8 type=1
sym lookup for _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE18option_takes_2argsEv from libdrltracelib.so
elf_sym_matches: considering type=2 _ZNK10droption_tINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEE18option_takes_2argsEv
<...>
XXX reloc @ 0x73870fec type=6
sym lookup for _ITM_registerTMCloneTable from libdrltracelib.so
sym lookup for _ITM_registerTMCloneTable from libdrltracelib.so = /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so
sym lookup for _ITM_registerTMCloneTable from libstdc++.so.6 = /usr/lib32/libstdc++.so.6
sym lookup for _ITM_registerTMCloneTable from libgcc_s.so.1 = /usr/lib32/libgcc_s.so.1
sym lookup for _ITM_registerTMCloneTable from libm.so.6 = /lib32/libm.so.6
sym lookup for _ITM_registerTMCloneTable from libc.so.6 = /lib32/libc.so.6
sym lookup for _ITM_registerTMCloneTable from ld-linux.so.2 = /lib/ld-linux.so.2
sym lookup for _ITM_registerTMCloneTable from libdynamorio.so = /home/bruening/drmemory/git/build_x86_dbg/dynamorio/lib32/debug/libdynamorio.so
symbol lookup for _ITM_registerTMCloneTable 0x00000000
XXX reloc @ 0x73870ff0 type=6
sym lookup for op_config_file_default from libdrltracelib.so
elf_sym_matches: considering type=1 op_config_file_default
symbol lookup for op_config_file_default 0x7388d740
XXX reloc @ 0x73871a4c type=1
sym lookup for __gxx_personality_v0 from libdrltracelib.so
sym lookup for __gxx_personality_v0 from libdrltracelib.so = /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so
sym lookup for __gxx_personality_v0 from libstdc++.so.6 = /usr/lib32/libstdc++.so.6
elf_sym_matches: considering type=2 __gxx_personality_v0
symbol lookup for __gxx_personality_v0 0xf79dd910
<========================== starts over here!!!!!!!! ===================================>
XXX reloc @ 0x73870bb4 type=8
XXX reloc @ 0x73870bb8 type=8
XXX reloc @ 0x73870bbc type=8
XXX reloc @ 0x73870bc4 type=8
<...>
XXX reloc @ 0x73870da4 type=1
<...>
symbol lookup for op_config_file_default 0x7388d740
XXX reloc @ 0x73871a4c type=1
sym lookup for __gxx_personality_v0 from libdrltracelib.so
sym lookup for __gxx_personality_v0 from libdrltracelib.so = /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so
sym lookup for __gxx_personality_v0 from libstdc++.so.6 = /usr/lib32/libstdc++.so.6
elf_sym_matches: considering type=2 __gxx_personality_v0
symbol lookup for __gxx_personality_v0 0xf79dd910
XXX reloc @ 0x7387100c type=7
```

```
$ egrep '^relocating|WALKING|73870da4|73870bb4|73871a4c|7387100c' `ls -1td dynamorio/logs/*0|head -1`/dr*
module_add_segment_data: #=3 0x73870bb4-0x7388e7d8 0x3
relocating ld-linux.so.2
WALKING rel 0xf77e48cc-0xf77e4a44
WALKING rel 0xf77e4a44-0xf77e4a7c
relocating libc.so.6
WALKING rel 0xf745963c-0xf745c16c
WALKING rel 0xf745c16c-0xf745c1cc
relocating libm.so.6
WALKING rel 0xf781cdd8-0xf781ce48
WALKING rel 0xf781ce48-0xf781cef0
relocating libgcc_s.so.1
WALKING rel 0xf77c5c7c-0xf77c5cd4
WALKING rel 0xf77c5cd4-0xf77c5e34
relocating libstdc++.so.6
WALKING rel 0xf79834e8-0xf798b6c0
WALKING rel 0xf798b6c0-0xf798d6f8
relocating libdrltracelib.so
WALKING rel 0x73810858-0x738124d0
XXX reloc @ 0x73870bb4 type=8
XXX reloc @ 0x73870da4 type=1
XXX reloc @ 0x73871a4c type=1
WALKING rel 0x73810858-0x73813928
XXX reloc @ 0x73870bb4 type=8
XXX reloc @ 0x73870da4 type=1
XXX reloc @ 0x73871a4c type=1
XXX reloc @ 0x7387100c type=7
```

So they all have 2 passes: it's in privload_relocate_os_privmod_data(),
opd->rel (DT_REL) and opd->jmprel (DT_JMPREL).  Other libs seem to have
zero overlap.
```
    if (opd->rel != NULL) {
        module_relocate_rel(mod_base, opd, opd->rel, opd->rel + opd->relsz / opd->relent);
    }
    if (opd->jmprel != NULL) {
        if (opd->pltrel == DT_REL) {
            module_relocate_rel(mod_base, opd, (ELF_REL_TYPE *)opd->jmprel,
                                (ELF_REL_TYPE *)(opd->jmprel + opd->pltrelsz));
```

Hmm.
```
$ readelf -r /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so
Relocation section '.rel.dyn' at offset 0x10858 contains 1562 entries:

$ readelf -d /home/bruening/drmemory/git/build_x86_dbg/bin/debug/libdrltracelib.so  
Dynamic section at offset 0x6fe40 contains 32 entries:
  Tag        Type                         Name/Value
<...>
 0x00000003 (PLTGOT)                     0x73871000
 0x00000002 (PLTRELSZ)                   12496 (bytes)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0x73810858
 0x00000011 (REL)                        0x73810858
 0x00000012 (RELSZ)                      7288 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x0000001e (FLAGS)                      BIND_NOW
 0x6ffffffb (FLAGS_1)                    Flags: NOW
<...>
 0x6ffffffa (RELCOUNT)                   819
```

7288/8 = 911
12496/8 = 1562

libm:
```
$ readelf -d /lib/i386-linux-gnu/libm.so.6
 0x00000002 (PLTRELSZ)                   168 (bytes)
 0x00000014 (PLTREL)                     REL
 0x00000017 (JMPREL)                     0xbe48
 0x00000011 (REL)                        0xbdd8
 0x00000012 (RELSZ)                      112 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x6ffffffa (RELCOUNT)                   4
```

Aha:
```
elf/dynamic-link.h:/* On some machines, notably SPARC, DT_REL* includes DT_JMPREL in its
elf/dynamic-link.h-   range.  Note that according to the ELF spec, this is completely legal!
elf/dynamic-link.h-
elf/dynamic-link.h:   We are guarenteed that we have one of three situations.  Either DT_JMPREL
elf/dynamic-link.h:   comes immediately after DT_REL*, or there is overlap and DT_JMPREL
elf/dynamic-link.h:   consumes precisely the very end of the DT_REL*, or DT_JMPREL and DT_REL*
elf/dynamic-link.h-   are completely separate and there is a gap between them.  */
elf/dynamic-link.h-
elf/dynamic-link.h-# define _ELF_DYNAMIC_DO_RELOC(RELOC, reloc, map, do_lazy, skip_ifunc, test_rel) \
```

It seems rather ugly for a new toolchain to generate an overlapping JMPREL though.
