### ISSUE TITLE
burst_threadL0filter assert failure on A64: instru_offline.cpp:413:   stamp->timestamp.type == OFFLINE_TYPE_TIMESTAMP

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5774]
The burst_threadL0filter test failed on the Jenkins CI failed on #5772:

```
34/84 Test #257: code_api|tool.drcacheoff.burst_threadL0filter ...................***Failed    0.18 sec
Running cmd |/var/lib/jenkins/workspace/DynamoRIO-AArch64-Precommit/build/build_release-external-64/clients/bin64/tool.drcacheoff.burst_threadfilter;-L0_filter -L0I_size 0 -subdir_prefix tool.drcacheoff.burst_threadL0filter|
CMake Error at /var/lib/jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/tests/runmulti.cmake:108 (message):
  *** cmd failed (255): pre-DR init

  pre-DR start

  pre-DR detach

  ASSERT FAILURE:
  /var/lib/jenkins/workspace/DynamoRIO-AArch64-Precommit/clients/drcachesim/tracer/instru_offline.cpp:413:
  stamp->timestamp.type == OFFLINE_TYPE_TIMESTAMP ()

  ***

Call Stack (most recent call first):
  /var/lib/jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/tests/runmulti.cmake:117 (process_cmdline)
```

**Comment by derekbruening** [comment]
That's the -align_endpoints timestamp update

**Comment by derekbruening** [comment]
I reproduced this in debug build on the Jenkins machine:
```
pre-DR start
pre-DR detach
pre-DR init
pre-DR start
pre-DR detach
ASSERT FAILURE: /home/derek/dr/src/clients/drcachesim/tracer/instru_offline.cpp:413: stamp->timestamp.type == OFFLINE_TYPE_TIMESTAMP ()
[Switching to Thread 0xfffff5ae81c0 (LWP 1389991)]

Thread 6 "tool.drcacheoff" hit Breakpoint 1, dr_abort () at /home/derek/dr/src/core/lib/instrument.c:2428
2428	    if (TEST(DUMPCORE_DR_ABORT, dynamo_options.dumpcore_mask))
(gdb) bt
#0  dr_abort () at /home/derek/dr/src/core/lib/instrument.c:2428
#1  0x0000aaaaaaea6de4 in offline_instru_t::refresh_unit_header_timestamp (this=0xaaaa6aab3148, buf_ptr=0xfffdef3b5000 "\212\001", min_timestamp=13314474307288391)
    at /home/derek/dr/src/clients/drcachesim/tracer/instru_offline.cpp:413
#2  0x0000aaaaaaea2594 in dynamorio::drmemtrace::process_and_output_buffer (drcontext=0xfffdf0c72b40, skip_size_cap=false)
    at /home/derek/dr/src/clients/drcachesim/tracer/output.cpp:938
#3  0x0000aaaaaaea3608 in dynamorio::drmemtrace::exit_thread_io (drcontext=0xfffdf0c72b40) at /home/derek/dr/src/clients/drcachesim/tracer/output.cpp:1186
#4  0x0000aaaaaae99ab0 in dynamorio::drmemtrace::event_thread_exit (drcontext=0xfffdf0c72b40) at /home/derek/dr/src/clients/drcachesim/tracer/tracer.cpp:1593
#5  0x0000aaaaaaf10d24 in drmgr_thread_exit_event (drcontext=0xfffdf0c72b40) at /home/derek/dr/src/ext/drmgr/drmgr.c:2662
#6  0x0000aaaaaac9a2f0 in instrument_thread_exit_event (dcontext=0xfffdf0c72b40) at /home/derek/dr/src/core/lib/instrument.c:1522
#7  0x0000aaaaaaaf3f20 in dynamo_thread_exit_pre_client (dcontext=0xfffdf0c72b40, id=1389982) at /home/derek/dr/src/core/dynamo.c:2470
#8  0x0000aaaaaaaf41e0 in dynamo_thread_exit_common (dcontext=0xfffdf0c72b40, id=1389982, other_thread=true) at /home/derek/dr/src/core/dynamo.c:2569
#9  0x0000aaaaaaaf4b1c in dynamo_other_thread_exit (tr=0xfffdf0c731d0) at /home/derek/dr/src/core/dynamo.c:2707
#10 0x0000aaaaaac8b2b4 in detach_on_permanent_stack (internal=true, do_cleanup=true, drstats=0x0) at /home/derek/dr/src/core/synch.c:2244
#11 0x0000aaaaaaaf4f54 in dr_app_stop_and_cleanup_with_stats (drstats=0x0) at /home/derek/dr/src/core/dynamo.c:2835
#12 0x0000aaaaaaaf4ee0 in dr_app_stop_and_cleanup () at /home/derek/dr/src/core/dynamo.c:2818
#13 0x0000aaaaaaada150 in thread_func (arg=0x4) at /home/derek/dr/src/clients/drcachesim/tests/burst_threadfilter.cpp:187
#14 0x0000fffff7fa351c in start_thread (arg=0xfffffffff1ef) at pthread_create.c:477
#15 0x0000fffff7bc222c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:78
```
